<?php
ob_start();
function opf_email_reply($ok,$message,$status=200,$extra=array()){while(ob_get_level()>0){ob_end_clean();}header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('X-Content-Type-Options: nosniff');$payload=array_merge(array('success'=>(bool)$ok,'message'=>(string)$message),is_array($extra)?$extra:array());http_response_code((int)$status);$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);echo is_string($json)?$json:'{"success":false}';exit;}
$requestLanguage=strtoupper(substr((string)($_SERVER['HTTP_ACCEPT_LANGUAGE']??'EN'),0,2));if(!preg_match('/^[A-Z]{2}$/D',$requestLanguage))$requestLanguage='EN';require __DIR__.'/languages/EN.php';$requestFallback=$OPF;if($requestLanguage!=='EN'&&is_readable(__DIR__.'/languages/'.$requestLanguage.'.php'))require __DIR__.'/languages/'.$requestLanguage.'.php';$OPF=array_merge($requestFallback,is_array($OPF)?$OPF:array());
$config=dirname(__DIR__,2).'/config.php';if(!is_readable($config))opf_email_reply(false,$OPF['CONFIGURATION_UNAVAILABLE'],500);require_once $config;require_once WB_PATH.'/framework/Admin.php';
$language=defined('LANGUAGE')?strtoupper((string)LANGUAGE):'EN';require __DIR__.'/languages/EN.php';$fallback=$OPF;if($language!=='EN'&&preg_match('/^[A-Z]{2}$/',$language)&&is_readable(__DIR__.'/languages/'.$language.'.php'))require __DIR__.'/languages/'.$language.'.php';$OPF=array_merge($fallback,is_array($OPF)?$OPF:array());
$admin=new admin('admintools','admintools',false);if(!$admin->is_authenticated()||!$admin->get_permission('mod_opf_email','module'))opf_email_reply(false,$OPF['FORBIDDEN'],403);$requestMethod=isset($_SERVER['REQUEST_METHOD'])&&is_string($_SERVER['REQUEST_METHOD'])?$_SERVER['REQUEST_METHOD']:'GET';if($requestMethod!=='POST'||!$admin->checkFTAN())opf_email_reply(false,$OPF['SECURITY_ERROR'],403,array('ftan'=>$admin->getFTAN()));
$scalar=static function($key){return isset($_POST[$key])&&is_scalar($_POST[$key])?(string)$_POST[$key]:'';};$data=array('email_filter'=>$scalar('email_filter')==='1'?1:0,'mailto_filter'=>$scalar('mailto_filter')==='1'?1:0,'js_mailto'=>$scalar('js_mailto')==='1'?1:0,'at_replacement'=>trim(strip_tags($scalar('at_replacement'))),'dot_replacement'=>trim(strip_tags($scalar('dot_replacement'))));if(!$data['mailto_filter'])$data['js_mailto']=0;if(strlen($data['at_replacement'])>80||strlen($data['dot_replacement'])>80)opf_email_reply(false,$OPF['INVALID'],422,array('ftan'=>$admin->getFTAN()));
$errors=array();foreach(array('opf_email_filter'=>'email_filter','opf_mailto_filter'=>'mailto_filter','opf_js_mailto'=>'js_mailto','opf_at_replacement'=>'at_replacement','opf_dot_replacement'=>'dot_replacement') as $setting=>$key){$result=Settings::Set($setting,$data[$key]);if($result!==false&&$result!==null&&$result!=='')$errors[]=(string)$result;}if($errors)opf_email_reply(false,$OPF['SAVE_FAILED'],500,array('ftan'=>$admin->getFTAN()));
if(file_exists(WB_PATH.'/modules/outputfilter_dashboard/functions.php'))require_once WB_PATH.'/modules/outputfilter_dashboard/functions.php';if(function_exists('opf_set_active'))opf_set_active('E-Mail Masking',($data['email_filter']||$data['mailto_filter']||$data['js_mailto'])?1:0);$stored=array('email_filter'=>(bool)Settings::Get('opf_email_filter'),'mailto_filter'=>(bool)Settings::Get('opf_mailto_filter'),'js_mailto'=>(bool)Settings::Get('opf_js_mailto'),'at_replacement'=>(string)Settings::Get('opf_at_replacement'),'dot_replacement'=>(string)Settings::Get('opf_dot_replacement'));if($stored!==array('email_filter'=>(bool)$data['email_filter'],'mailto_filter'=>(bool)$data['mailto_filter'],'js_mailto'=>(bool)$data['js_mailto'],'at_replacement'=>$data['at_replacement'],'dot_replacement'=>$data['dot_replacement']))opf_email_reply(false,$OPF['SAVE_NOT_CONFIRMED'],500,array('settings'=>$stored,'ftan'=>$admin->getFTAN()));opf_email_reply(true,$OPF['SAVED'],200,array('settings'=>$stored,'ftan'=>$admin->getFTAN()));
