<?php
return array(
 'admin_title'=>'2FA Authentifizierung','admin_intro'=>'Installierte Anmeldeverfahren auswählen und konfigurieren.','active'=>'Aktiv','inactive'=>'Inaktiv',
 'selected'=>'Ausgewählt','used'=>'Bereits verwendet','available'=>'Verfügbar','configured'=>'Eingerichtet','not_configured'=>'Nicht eingerichtet','configure'=>'Einrichten','settings'=>'Einstellungen','back'=>'Zurück','close'=>'Schließen','users_configured'=>'{count} Benutzer eingerichtet','not_selectable'=>'Nicht auswählbar','select_provider'=>'Provider auswählen',
 'provider_settings'=>'Provider-Einstellungen','provider_settings_hint'=>'Providerdaten und Benutzereinrichtungen bleiben bei einem Wechsel gespeichert.','open_settings'=>'Einstellungen öffnen',
 'switch_title'=>'2FA-Provider wechseln?','switch_data_kept'=>'Bestehende Provider- und Benutzerdaten werden nicht gelöscht.','warning_understood'=>'Warnung verstanden','switch_final_warning'=>'Der Wechsel kann die Anmeldung eingerichteter Benutzer beeinflussen. Wirklich fortfahren?','cancel'=>'Abbrechen','switch_confirm'=>'Endgültig wechseln',
 'security_expired'=>'Die Sicherheitsprüfung ist abgelaufen.','database_unavailable'=>'Die WBCE-Datenbank ist nicht verfügbar.','status_save_failed'=>'Der Status konnte nicht gespeichert werden.','enabled_message'=>'2FA Authentifizierung ist aktiviert.','disabled_message'=>'2FA Authentifizierung ist deaktiviert. Providerdaten bleiben gespeichert.',
 'provider_missing'=>'Der Provider ist nicht installiert.','provider_used_target'=>'Dieser Provider wird bereits verwendet und ist deshalb nicht als Wechselziel verfügbar.','confirmation_missing'=>'Die zweistufige Bestätigung fehlt.','selection_failed'=>'Die Auswahl konnte nicht gespeichert werden.','provider_selected'=>'Provider „{provider}“ wurde ausgewählt. Gespeicherte Einstellungen bleiben erhalten.','save_failed'=>'Speichern fehlgeschlagen','saving'=>'Wird gespeichert …','current_provider_usage'=>'Der bisherige Provider ist bei {count} Benutzer(n) eingerichtet.',
 'invalid_provider_id'=>'Ungültige 2FA-Provider-ID.','last_provider'=>'Der letzte installierte 2FA-Provider kann bei aktiver 2FA nicht deinstalliert werden. Installieren Sie zuerst einen anderen Provider oder deaktivieren Sie 2FA systemweit.',
 'provider_requires_core'=>'Dieser 2FA-Provider benötigt das installierte Grundmodul „2FA Authentifizierung“.','provider_config_saved'=>'Die Provider-Einstellungen wurden gespeichert.','provider_enabled'=>'Der Provider wurde aktiviert.','provider_disabled'=>'Der Provider wurde deaktiviert.','no_enabled_provider'=>'Aktivieren Sie zuerst mindestens einen 2FA-Provider.','admin_provider_not_configured'=>'Richten Sie diesen Provider zuerst vollständig ein, bevor Sie ihn aktivieren.','user_section_title'=>'Zwei-Faktor-Authentifizierung','user_section_intro'=>'Richten Sie freigegebene Verfahren ein und wählen Sie genau eines für Ihre Anmeldung.','user_provider_ready'=>'Vollständig eingerichtet und zur Auswahl bereit.','user_provider_setup'=>'Noch nicht vollständig eingerichtet.','setup_provider'=>'Einrichten','manage'=>'Verwalten','use_provider'=>'Für Anmeldung verwenden','disable_personal'=>'2FA für mein Benutzerkonto deaktivieren','personal_disabled_status'=>'2FA ist für dieses Benutzerkonto deaktiviert. Eingerichtete Providerdaten bleiben gespeichert.','provider_not_configured'=>'Dieser Provider ist für Ihr Benutzerkonto noch nicht vollständig eingerichtet.','no_provider_title'=>'Kein 2FA-Provider installiert','no_provider_hint'=>'Installiere zuerst einen kompatiblen Provider. Bis dahin bleibt die 2FA Authentifizierung sicher deaktiviert.',
 'disable_confirm_title'=>'2FA sicher deaktivieren','disable_confirm_intro'=>'Bestätigen Sie zuerst Ihr aktuelles Kontopasswort. Anschließend wird Ihr derzeit verwendeter zweiter Faktor geprüft.','current_password'=>'Aktuelles Passwort','continue'=>'Weiter','factor_confirmation'=>'Zweiten Faktor bestätigen','current_factor_code'=>'Aktueller 2FA-Code oder Backupcode','confirm_disable'=>'2FA endgültig deaktivieren','password_invalid'=>'Das aktuelle Passwort ist nicht korrekt.','factor_invalid'=>'Der zweite Faktor konnte nicht bestätigt werden.','factor_unavailable'=>'Der aktive 2FA-Provider unterstützt diese Sicherheitsprüfung nicht.','use_security_key'=>'Mit Sicherheitsschlüssel bestätigen','code_sent'=>'Ein neuer Bestätigungscode wurde versendet.','deactivated'=>'2FA wurde für Ihr Benutzerkonto deaktiviert.',
 'precheck_hooks_label'=>'Hook-Schnittstellen','precheck_hooks_required'=>'WBCE 1.7.0 oder Hook-Bridge 1.2.0','precheck_available'=>'Verfügbar','precheck_unavailable'=>'Nicht verfügbar'
);
