<?php
return array(
 'admin_title'=>'2FA Authentication','admin_intro'=>'Select and configure installed sign-in methods.','active'=>'Active','inactive'=>'Inactive',
 'selected'=>'Selected','used'=>'Already in use','available'=>'Available','configured'=>'Configured','not_configured'=>'Not configured','configure'=>'Set up','settings'=>'Settings','back'=>'Back','close'=>'Close','users_configured'=>'{count} users configured','not_selectable'=>'Not selectable','select_provider'=>'Select provider',
 'provider_settings'=>'Provider settings','provider_settings_hint'=>'Provider and user data remain stored when switching.','open_settings'=>'Open settings',
 'switch_title'=>'Change 2FA provider?','switch_data_kept'=>'Existing provider and user data will not be deleted.','warning_understood'=>'I understand','switch_final_warning'=>'Changing the provider can affect sign-in for configured users. Continue?','cancel'=>'Cancel','switch_confirm'=>'Change provider',
 'security_expired'=>'The security token has expired.','database_unavailable'=>'The WBCE database is unavailable.','status_save_failed'=>'The status could not be saved.','enabled_message'=>'Two-factor authentication is enabled.','disabled_message'=>'Two-factor authentication is disabled. Provider data remains stored.',
 'provider_missing'=>'The provider is not installed.','provider_used_target'=>'This provider is already in use and cannot be selected as a switch target.','confirmation_missing'=>'The two-step confirmation is missing.','selection_failed'=>'The selection could not be saved.','provider_selected'=>'Provider “{provider}” was selected. Stored settings remain available.','save_failed'=>'Saving failed','saving'=>'Saving …','current_provider_usage'=>'The current provider is configured for {count} user(s).',
 'invalid_provider_id'=>'Invalid 2FA provider ID.','last_provider'=>'The last installed 2FA provider cannot be uninstalled while 2FA is active. Install another provider or disable 2FA system-wide first.',
 'provider_requires_core'=>'This 2FA provider requires the installed “2FA Authentication” core module.','provider_config_saved'=>'The provider settings were saved.','provider_enabled'=>'The provider was enabled.','provider_disabled'=>'The provider was disabled.','no_enabled_provider'=>'Enable at least one 2FA provider first.','admin_provider_not_configured'=>'Complete this provider’s setup before enabling it.','user_section_title'=>'2FA Authentication','user_section_intro'=>'Configure allowed methods and select exactly one for sign-in.','user_provider_ready'=>'Fully configured and ready to select.','user_provider_setup'=>'Not fully configured yet.','setup_provider'=>'Set up','manage'=>'Manage','use_provider'=>'Use for sign-in','disable_personal'=>'Disable 2FA for my account','personal_disabled_status'=>'2FA is disabled for this account. Configured provider data remains stored.','provider_not_configured'=>'This provider is not fully configured for your account.','no_provider_title'=>'No 2FA provider installed','no_provider_hint'=>'Install a compatible provider first. Until then, 2FA Authentication remains safely disabled.',
 'disable_confirm_title'=>'Disable 2FA securely','disable_confirm_intro'=>'First confirm your current account password. Your active second factor will then be verified.','current_password'=>'Current password','continue'=>'Continue','factor_confirmation'=>'Confirm second factor','current_factor_code'=>'Current 2FA code or backup code','confirm_disable'=>'Disable 2FA permanently','password_invalid'=>'The current password is incorrect.','factor_invalid'=>'The second factor could not be verified.','factor_unavailable'=>'The active 2FA provider does not support this security check.','use_security_key'=>'Confirm with security key','code_sent'=>'A new confirmation code has been sent.','deactivated'=>'2FA has been disabled for your account.',
 'precheck_hooks_label'=>'Hook interfaces','precheck_hooks_required'=>'WBCE 1.7.0 or Hook Bridge 1.2.0','precheck_available'=>'Available','precheck_unavailable'=>'Unavailable'
);
