<?php
require_once '../../config.php';require_once WB_PATH.'/framework/Admin.php';require_once WB_PATH.'/modules/two_factor/Language.php';require_once WB_PATH.'/modules/two_factor/Settings.php';require_once WB_PATH.'/modules/two_factor/EmbeddedView.php';require_once __DIR__.'/Service.php';header('X-Frame-Options: SAMEORIGIN');header("Content-Security-Policy: frame-ancestors 'self'");header('Referrer-Policy: same-origin');
$admin=new admin('Preferences','start',false);if(!WbceTwoFactorSettings::enabled($database)||!WbceTwoFactorSettings::providerEnabled($database,'webauthn')){header('Location: '.ADMIN_URL.'/preferences/');exit;}
$s=new WbceWebAuthnService($database);$uid=(int)$admin->get_user_id();
if(isset($_GET['options'])){while(ob_get_level()>0&&!ob_end_clean())break;header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');echo json_encode($s->registrationOptions($uid,method_exists($admin,'get_username')?$admin->get_username():$admin->get_email(),method_exists($admin,'get_display_name')?$admin->get_display_name():$admin->get_email()));exit;}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){while(ob_get_level()>0&&!ob_end_clean())break;header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');try{if(!$admin->checkFTAN())throw new RuntimeException(wbce_two_factor_t('security_expired',array(),'two_factor_webauthn'));$action=isset($_POST['action'])&&is_scalar($_POST['action'])?(string)$_POST['action']:'';if($action==='register'){$raw=isset($_POST['credential'])&&is_scalar($_POST['credential'])?(string)$_POST['credential']:'';$payload=json_decode($raw,true);if(!is_array($payload))throw new RuntimeException(wbce_two_factor_t('invalid_device',array(),'two_factor_webauthn'));$label=isset($_POST['label'])&&is_scalar($_POST['label'])?(string)$_POST['label']:'';$s->register($uid,$payload,$label);$message=wbce_two_factor_t('registered',array(),'two_factor_webauthn');}elseif($action==='remove'){$id=isset($_POST['id'])&&is_scalar($_POST['id'])?(int)$_POST['id']:0;if(count($s->credentials($uid))<=1&&WbceTwoFactorSettings::userProvider($database,$uid)==='webauthn')throw new RuntimeException(wbce_two_factor_t('cannot_remove_last',array(),'two_factor_webauthn'));if($id<1||!$s->remove($uid,$id))throw new RuntimeException(wbce_two_factor_t('remove_failed',array(),'two_factor_webauthn'));$message=wbce_two_factor_t('removed',array(),'two_factor_webauthn');}else throw new RuntimeException(wbce_two_factor_t('unknown_action',array(),'two_factor_webauthn'));echo json_encode(array('success'=>true,'message'=>$message,'ftan'=>$admin->getFTAN()));}catch(Throwable $e){http_response_code(422);echo json_encode(array('success'=>false,'message'=>$e->getMessage(),'ftan'=>$admin->getFTAN()));}exit;}
$credentials=$s->credentials($uid);$embedded=WbceTwoFactorEmbeddedView::start();if(!$embedded)$admin->print_header();function wak_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}$endpoint=WB_URL.'/modules/two_factor_webauthn/profile.php'.($embedded?'?embedded=1':'');
?>
<link rel="stylesheet" href="<?php echo wak_h(WB_URL.'/modules/two_factor/admin-ui.css?v=1.1.34');?>">
<div class="wak wbce-admin-tool-shell tf-provider-profile" data-webauthn-endpoint="<?php echo wak_h($endpoint);?>" data-action-failed="<?php echo wak_h(wbce_two_factor_t('action_failed',array(),'two_factor_webauthn'));?>" data-check-failed="<?php echo wak_h(wbce_two_factor_t('checking',array(),'two_factor_webauthn'));?>" data-remove-confirm="<?php echo wak_h(wbce_two_factor_t('remove_confirm',array(),'two_factor_webauthn'));?>" data-cancel="<?php echo wak_h(wbce_two_factor_t('cancel',array(),'two_factor_webauthn'));?>" data-confirm="<?php echo wak_h(wbce_two_factor_t('confirm',array(),'two_factor_webauthn'));?>">
 <section class="content-box wbce-admin-card tf-provider-intro"><h2><?php echo wak_h(wbce_two_factor_t('title',array(),'two_factor_webauthn'));?></h2><p><?php echo wak_h(wbce_two_factor_t('profile_intro',array(),'two_factor_webauthn'));?></p></section>
 <section class="content-box wbce-admin-card wak-register-card"><h3><?php echo wak_h(wbce_two_factor_t('new_device',array(),'two_factor_webauthn'));?></h3><div class="wak-register-fields"><label><?php echo wak_h(wbce_two_factor_t('label',array(),'two_factor_webauthn'));?><input class="form-control" id="wak-label" value="<?php echo wak_h(wbce_two_factor_t('default_label',array(),'two_factor_webauthn'));?>" maxlength="190"></label><button type="button" class="button wbce-admin-button" id="wak-register"><?php echo wak_h(wbce_two_factor_t('add',array(),'two_factor_webauthn'));?></button></div><p><small><?php echo wak_h(wbce_two_factor_t('https_hint',array(),'two_factor_webauthn'));?></small></p></section>
 <section class="content-box wbce-admin-card"><h3><?php echo wak_h(wbce_two_factor_t('configured_devices',array(),'two_factor_webauthn'));?></h3><div id="wak-list" class="tf-device-list"><?php if(!$credentials):?><p data-empty><?php echo wak_h(wbce_two_factor_t('none',array(),'two_factor_webauthn'));?></p><?php endif;?><?php foreach($credentials as $c):?><article data-device="<?php echo (int)$c['id'];?>"><div><strong><?php echo wak_h($c['label']);?></strong><small><?php echo wak_h(wbce_two_factor_t('configured_at',array('date'=>date('d.m.Y H:i',(int)$c['created_at'])),'two_factor_webauthn'));?></small></div><button type="button" class="button wbce-admin-button" data-remove="<?php echo (int)$c['id'];?>"><?php echo wak_h(wbce_two_factor_t('remove',array(),'two_factor_webauthn'));?></button></article><?php endforeach;?></div></section>
 <form id="wak-token" hidden><?php echo $admin->getFTAN();?></form><div class="wak-toast tf-profile-toast" hidden aria-live="polite"></div>
 <?php if(!$embedded):?><p><a class="button" href="<?php echo ADMIN_URL;?>/preferences/"><?php echo wak_h(wbce_two_factor_t('back',array(),'two_factor_webauthn'));?></a></p><?php endif;?>
</div>
<script src="<?php echo wak_h(WB_URL.'/modules/two_factor_webauthn/profile.js?v=1.1.17');?>"></script>
<?php if($embedded)WbceTwoFactorEmbeddedView::end();else $admin->print_footer();
