<?php
require_once __DIR__.'/Service.php';
require_once WB_PATH.'/modules/two_factor/Language.php';
final class WbceWebAuthnProvider implements WbceAuthFactorProviderInterface
{
 private $service;public function __construct($db){$this->service=new WbceWebAuthnService($db);}public function getId(){return 'webauthn';}
 public function isRequired(array $user){global $database;require_once WB_PATH.'/modules/two_factor/Settings.php';return WbceTwoFactorSettings::enabled($database)&&WbceTwoFactorSettings::userProvider($database,(int)$user['user_id'])==='webauthn'&&$this->service->isEnabled($user['user_id']);}
 public function renderChallenge(array $user,$error=''){$options=$this->service->assertionOptions($user['user_id']);$json=htmlspecialchars(json_encode($options),ENT_QUOTES,'UTF-8');require_once WB_PATH.'/modules/two_factor/ChallengeView.php';$failed=json_encode(wbce_two_factor_t('verification_failed',array(),'two_factor_webauthn'),JSON_UNESCAPED_UNICODE);$field='<input type="hidden" name="factor_code" id="webauthn-result"><button type="button" id="webauthn-start">'.htmlspecialchars(wbce_two_factor_t('use_key',array(),'two_factor_webauthn'),ENT_QUOTES,'UTF-8').'</button><span id="webauthn-status" role="status"></span><script>!function(){const o=JSON.parse(document.getElementById("webauthn-options").textContent),d=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)),c=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,""),run=async()=>{const s=document.getElementById("webauthn-status");try{o.challenge=d(o.challenge);o.allowCredentials=(o.allowCredentials||[]).map(x=>({...x,id:d(x.id)}));const r=await navigator.credentials.get({publicKey:o});document.getElementById("webauthn-result").value=JSON.stringify({id:r.id,type:r.type,response:{clientDataJSON:c(r.response.clientDataJSON),authenticatorData:c(r.response.authenticatorData),signature:c(r.response.signature),userHandle:r.response.userHandle?c(r.response.userHandle):null}});document.getElementById("wbce-auth-factor").submit()}catch(e){s.textContent='.$failed.'}};document.getElementById("webauthn-start").onclick=run}();</script><script type="application/json" id="webauthn-options">'.$json.'</script>';
  $rawJson=json_encode($options,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);
  $field=str_replace($json,$rawJson,$field);
  return WbceTwoFactorChallengeView::render('webauthn',wbce_two_factor_t('challenge_description',array(),'two_factor_webauthn'),wbce_two_factor_t('device_check',array(),'two_factor_webauthn'),$field,'',$error);}
 public function verify(array $user,array $input){$payload=json_decode((string)($input['factor_code']??''),true);if(!is_array($payload))return false;$auth=WbceWebAuthnService::b64d($payload['response']['authenticatorData']??'');if($this->service->setting('user_verification','preferred')==='required'&&(!is_string($auth)||strlen($auth)<33||(ord($auth[32])&4)!==4))return false;return $this->service->verify($user['user_id'],$payload);}
}
