<?php
defined('WB_PATH') or die('No direct access');
if(!class_exists('WbceCaptchaManager')){
final class WbceCaptchaManager
{
 private static $legacy=array('calc_text','calc_image','calc_ttf_image','ttf_image','old_image','text');
 public static function providers(array $labels=array()){$all=array();foreach(self::$legacy as $id)$all[$id]=array('id'=>$id,'name'=>$labels[$id]??$id,'description'=>'','legacy'=>true);$all=function_exists('wbce_apply_array_filters')?wbce_apply_array_filters('captcha.providers',$all):$all;foreach($all as $id=>&$p){if(!is_array($p)){unset($all[$id]);continue;}$p+=array('id'=>$id,'name'=>$id,'description'=>'','legacy'=>false);}unset($p);return $all;}
 public static function selected(array $labels=array()){$id=defined('CAPTCHA_TYPE')?(string)CAPTCHA_TYPE:(class_exists('Settings')?(string)Settings::Get('captcha_type','altcha'):'altcha');$all=self::providers($labels);return $all[$id]??null;}
 public static function isLegacy($id){return in_array((string)$id,self::$legacy,true);}public static function render($action='all',$style='',$sectionId='',array $context=array()){$p=self::selected();if(!$p||!empty($p['legacy'])||empty($p['render'])||!is_callable($p['render']))return false;$context+=array('action'=>$action,'style'=>$style,'section_id'=>$sectionId,'field_name'=>'captcha');echo (string)call_user_func($p['render'],$context);if(function_exists('wbce_do_action'))wbce_do_action('captcha.rendered',$p['id'],$context);return true;}
 public static function verify($input=null,$sectionId='',array $context=array()){$p=self::selected();if(!$p)return false;$context+=array('section_id'=>$sectionId,'request'=>$_POST,'remote_address'=>$_SERVER['REMOTE_ADDR']??'');if(!empty($p['legacy'])){$value=$input??($_POST['captcha']??null);$expected=array_filter(array($_SESSION['captcha']??null,$sectionId!==''?($_SESSION['captcha'.$sectionId]??null):null),static function($v){return $v!==null;});$valid=false;if($value!==null&&$value!==''){foreach($expected as $candidate){if(hash_equals((string)$candidate,(string)$value)){$valid=true;break;}}}}else{$valid=!empty($p['verify'])&&is_callable($p['verify'])?(bool)call_user_func($p['verify'],$input,$context):false;}if(function_exists('wbce_apply_filters'))$valid=(bool)wbce_apply_filters('captcha.validation.result',$valid,$p['id'],$context);if(function_exists('wbce_do_action'))wbce_do_action($valid?'captcha.verified':'captcha.failed',$p['id'],$context);return $valid;}
}
}
if(!function_exists('wbce_captcha_providers')){function wbce_captcha_providers(array $labels=array()){return WbceCaptchaManager::providers($labels);}function wbce_captcha_render($action='all',$style='',$sectionId='',array $context=array()){return WbceCaptchaManager::render($action,$style,$sectionId,$context);}function wbce_captcha_verify($input=null,$sectionId='',array $context=array()){return WbceCaptchaManager::verify($input,$sectionId,$context);}function wbce_captcha_is_enabled($purpose){if(!class_exists('Settings'))return false;if($purpose==='login')return(string)Settings::Get('captcha_login_mode','after_failures')!=='off';if($purpose==='password_reset')return(string)Settings::Get('captcha_password_reset','1')==='1';$value=defined('ENABLED_CAPTCHA')?ENABLED_CAPTCHA:Settings::Get('enabled_captcha',true);return(bool)filter_var($value,FILTER_VALIDATE_BOOLEAN);}}
