<?php
defined('WBCE_TWO_FACTOR_FALLBACK_MANAGER') || define('WBCE_TWO_FACTOR_FALLBACK_MANAGER', true);
final class WbceAuthFactorManager
{
 const SESSION_KEY='WBCE_AUTH_FACTOR_CHALLENGE',VERIFIED_KEY='WBCE_AUTH_FACTOR_VERIFIED',LIFETIME=300;private static $providers=array();
 public static function register(WbceAuthFactorProviderInterface $p){self::$providers[$p->getId()]=$p;}public static function provider($id){return self::$providers[$id]??null;}
 public static function requiredProviderIds(array $u){$r=array();foreach(self::$providers as $id=>$p)if($p->isRequired($u))$r[]=$id;return function_exists('wbce_apply_filters')?wbce_apply_filters('auth.factors.required',$r,$u):$r;}
 public static function begin($uid,array $ids,$url){$_SESSION[self::SESSION_KEY]=array('user_id'=>(int)$uid,'providers'=>array_values($ids),'position'=>0,'attempts'=>0,'expires'=>time()+self::LIFETIME,'nonce'=>bin2hex(random_bytes(32)),'return_url'=>is_string($url)&&strpos($url,WB_URL)===0?$url:ADMIN_URL.'/start/index.php');if(function_exists('wbce_do_action'))wbce_do_action('auth.challenge.started',(int)$uid,$ids);}
 public static function current(){if(empty($_SESSION[self::SESSION_KEY])||!is_array($_SESSION[self::SESSION_KEY]))return null;if(empty($_SESSION[self::SESSION_KEY]['expires'])||$_SESSION[self::SESSION_KEY]['expires']<time()){self::cancel();return null;}return $_SESSION[self::SESSION_KEY];}
 public static function currentProvider(){$c=self::current();if(!$c)return null;$p=(int)$c['position'];return isset($c['providers'][$p])?self::provider($c['providers'][$p]):null;}public static function advance(){$_SESSION[self::SESSION_KEY]['position']++;return $_SESSION[self::SESSION_KEY]['position']>=count($_SESSION[self::SESSION_KEY]['providers']);}public static function recordFailure($max=10){if(empty($_SESSION[self::SESSION_KEY]))return true;if(++$_SESSION[self::SESSION_KEY]['attempts']>=(int)$max){self::cancel();return true;}return false;}public static function consume(){$c=self::current();unset($_SESSION[self::SESSION_KEY]);return $c;}public static function cancel(){unset($_SESSION[self::SESSION_KEY]);}public static function markVerified($uid){$_SESSION[self::VERIFIED_KEY]=array('user_id'=>(int)$uid,'session_id'=>session_id());}public static function isVerified($uid){return !empty($_SESSION[self::VERIFIED_KEY])&&(int)$_SESSION[self::VERIFIED_KEY]['user_id']===(int)$uid&&hash_equals((string)$_SESSION[self::VERIFIED_KEY]['session_id'],session_id());}
}
