<?php
return array(
 'back'=>'Zurück zu Meine Daten','cannot_remove_last'=>'Der aktuell verwendete letzte Passkey kann hier nicht entfernt werden. Deaktiviere 2FA zuerst über die geschützte zentrale Funktion unter Meine Daten.',
 'provider_name'=>'Passkeys & Sicherheitsschlüssel','provider_description'=>'Passkeys, Fingerabdruck, Gesichtserkennung sowie USB- und NFC-Sicherheitsschlüssel über WebAuthn.','preferences_active'=>'Für dein Konto sind Passkeys oder Sicherheitsschlüssel eingerichtet.','preferences_inactive'=>'Richte einen Passkey, deine Gerätebiometrie oder einen Sicherheitsschlüssel ein.','manage'=>'Geräte verwalten',
 'use_key'=>'Passkey oder Sicherheitsschlüssel verwenden','verification_failed'=>'Die Geräteprüfung wurde abgebrochen oder ist fehlgeschlagen.','cancel'=>'Abbrechen','confirm'=>'Entfernen','challenge_description'=>'Bestätige die Anmeldung mit deinem Passkey, deiner Gerätebiometrie oder einem USB-/NFC-Sicherheitsschlüssel.','device_check'=>'Geräteprüfung',
 'security_expired'=>'Die Sicherheitsprüfung ist abgelaufen.','invalid_device'=>'Ungültige Gerätedaten.','registered'=>'Passkey oder Sicherheitsschlüssel wurde eingerichtet.','removed'=>'Gerät wurde entfernt.','unknown_action'=>'Unbekannte Aktion.','title'=>'Passkeys & Sicherheitsschlüssel','profile_intro'=>'Biometrie, Passkeys sowie USB- und NFC-Schlüssel verwalten.','new_device'=>'Neues Gerät einrichten','label'=>'Bezeichnung','default_label'=>'Mein Passkey','add'=>'Passkey oder Schlüssel hinzufügen','https_hint'=>'Die Einrichtung benötigt HTTPS und einen WebAuthn-fähigen Browser.','configured_devices'=>'Eingerichtete Geräte','none'=>'Noch kein Gerät eingerichtet.','configured_at'=>'Eingerichtet: {date}','remove'=>'Entfernen','action_failed'=>'Aktion fehlgeschlagen','checking'=>'Geräteprüfung läuft …','remove_confirm'=>'Dieses Gerät wirklich entfernen?',
 'config_intro'=>'WebAuthn gilt immer nur für die HTTPS-Domain {domain}.','user_verification'=>'Benutzerprüfung','preferred'=>'Wenn verfügbar verwenden','required'=>'Immer verlangen','save'=>'Speichern','saving'=>'Wird gespeichert …','saved'=>'WebAuthn-Einstellungen wurden gespeichert.','invalid_selection'=>'Ungültige Auswahl.','provider_requires_core'=>'Dieser Provider benötigt das installierte Grundmodul 2FA Authentifizierung.',
 'request_invalid'=>'Die WebAuthn-Anfrage konnte nicht bestätigt werden.','registration_invalid'=>'Ungültige WebAuthn-Registrierung.','algorithm_unsupported'=>'Dieser Schlüsselalgorithmus wird nicht unterstützt.','credential_mismatch'=>'Die Schlüssel-ID stimmt nicht überein.','credential_save_failed'=>'Der Passkey konnte nicht gespeichert werden.','remove_failed'=>'Das Gerät konnte nicht entfernt werden.','cbor_invalid'=>'Ungültige CBOR-Daten.','cbor_type_unsupported'=>'Nicht unterstützter CBOR-Typ.','cbor_length_unsupported'=>'Nicht unterstützte CBOR-Länge.','database_unavailable'=>'Die Datenbankverbindung ist nicht verfügbar.','configuration_invalid'=>'Die WebAuthn-Domain ist ungültig konfiguriert.','session_unavailable'=>'Die sichere Sitzung ist nicht verfügbar.'
);
