<?php
return array(
 'back'=>'Back to My Data','cannot_remove_last'=>'The last passkey currently in use cannot be removed here. First disable 2FA using the protected central function under My Data.',
 'provider_name'=>'Passkeys & security keys','provider_description'=>'Passkeys, fingerprint, face recognition and USB/NFC security keys through WebAuthn.','preferences_active'=>'Passkeys or security keys are configured for your account.','preferences_inactive'=>'Configure a passkey, device biometrics or a security key.','manage'=>'Manage devices',
 'use_key'=>'Use passkey or security key','verification_failed'=>'Device verification was cancelled or failed.','cancel'=>'Cancel','confirm'=>'Remove','challenge_description'=>'Confirm sign-in with your passkey, device biometrics or USB/NFC security key.','device_check'=>'Device verification',
 'security_expired'=>'The security token has expired.','invalid_device'=>'Invalid device data.','registered'=>'Passkey or security key was added.','removed'=>'Device was removed.','unknown_action'=>'Unknown action.','title'=>'Passkeys & security keys','profile_intro'=>'Manage biometrics, passkeys and USB/NFC keys.','new_device'=>'Add a device','label'=>'Label','default_label'=>'My passkey','add'=>'Add passkey or key','https_hint'=>'Setup requires HTTPS and a WebAuthn-capable browser.','configured_devices'=>'Configured devices','none'=>'No device configured.','configured_at'=>'Configured: {date}','remove'=>'Remove','action_failed'=>'Action failed','checking'=>'Checking device …','remove_confirm'=>'Remove this device?',
 'config_intro'=>'WebAuthn always applies only to the HTTPS domain {domain}.','user_verification'=>'User verification','preferred'=>'Use when available','required'=>'Always require','save'=>'Save','saving'=>'Saving …','saved'=>'WebAuthn settings were saved.','invalid_selection'=>'Invalid selection.','provider_requires_core'=>'This provider requires the installed 2FA Authentication core module.',
 'request_invalid'=>'The WebAuthn request could not be verified.','registration_invalid'=>'Invalid WebAuthn registration.','algorithm_unsupported'=>'This key algorithm is not supported.','credential_mismatch'=>'The credential ID does not match.','credential_save_failed'=>'The passkey could not be saved.','remove_failed'=>'The device could not be removed.','cbor_invalid'=>'Invalid CBOR data.','cbor_type_unsupported'=>'Unsupported CBOR type.','cbor_length_unsupported'=>'Unsupported CBOR length.','database_unavailable'=>'The database connection is unavailable.','configuration_invalid'=>'The WebAuthn domain configuration is invalid.','session_unavailable'=>'The secure session is unavailable.'
);
