<?php
defined('WB_PATH') or die('No direct access');
if(!is_file(WB_PATH.'/modules/two_factor/Language.php')||!is_file(WB_PATH.'/modules/two_factor/Registry.php'))return;
require_once WB_PATH.'/modules/two_factor/Language.php';
if(is_file(WB_PATH.'/modules/two_factor/Compatibility.php'))require_once WB_PATH.'/modules/two_factor/Compatibility.php';
require_once WB_PATH.'/modules/two_factor/Registry.php';
require_once __DIR__.'/Service.php';
WbceTwoFactorRegistry::register('email',array(
 'module_directory'=>'two_factor_email','name'=>wbce_two_factor_t('provider_name',array(),'two_factor_email'),'description'=>wbce_two_factor_t('provider_description',array(),'two_factor_email'),'icon'=>'fa-envelope','usage'=>static function()use($database){return(new WbceEmailFactorService($database))->usage();},'profile_url'=>WB_URL.'/modules/two_factor_email/profile.php','configured'=>static function($userId)use($database){return(new WbceEmailFactorService($database))->isEnabled($userId);},'system_configured'=>static function()use($database){return(new WbceEmailFactorService($database))->isConfigured();},
 'disable_challenge'=>static function($userId)use($database){(new WbceEmailFactorService($database))->sendCode($userId,true);return array('type'=>'code','message'=>wbce_two_factor_t('code_sent'));},
 'verify_disable'=>static function($userId,$value)use($database){return(new WbceEmailFactorService($database))->verify($userId,$value);},
 'admin_config'=>static function()use($database){
  $s=new WbceEmailFactorService($database);$h=static function($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');};$languages=$s->installedLanguages();$preferred=defined('LANGUAGE')?strtoupper((string)LANGUAGE):'';if(!isset($languages[$preferred])){$keys=array_keys($languages);$preferred=(string)($keys[0]??'');}
  $templates=array();foreach($languages as $code=>$name){$subject=$s->setting('subject.'.$code,'');$message=$s->setting('message.'.$code,'');$templates[$code]=array('subject'=>$subject!==''?$subject:$s->textForLanguage('default_subject',$code),'message'=>$message!==''?$message:$s->textForLanguage('default_message',$code));}
  $current=$templates[$preferred]??array('subject'=>'','message'=>'');$html='<form class="two-factor-email-config"><label>'.$h(wbce_two_factor_t('validity',array(),'two_factor_email')).'<select name="validity"><option value="300"'.($s->setting('validity','300')==='300'?' selected':'').'>5 '.$h(wbce_two_factor_t('minutes',array(),'two_factor_email')).'</option><option value="600"'.($s->setting('validity')==='600'?' selected':'').'>10 '.$h(wbce_two_factor_t('minutes',array(),'two_factor_email')).'</option></select></label><label>'.$h(wbce_two_factor_t('edit_language',array(),'two_factor_email')).'<select name="target_language" data-email-language-picker>';
  foreach($languages as $code=>$name)$html.='<option value="'.$h($code).'"'.($code===$preferred?' selected':'').'>'.$h($name.' ('.$code.')').'</option>';
  $legend=wbce_two_factor_t('language_template',array('language'=>($languages[$preferred]??$preferred).' ('.$preferred.')'),'two_factor_email');
  $mailerReady=$s->isConfigured();
  $html.='</select></label><p class="wide tf-mailer-status'.($mailerReady?' is-ready':'').'"><small>'.$h(wbce_two_factor_t($mailerReady?'mailer_ready':'mailer_not_ready',array(),'two_factor_email')).'</small></p><p class="wide"><small>'.$h(wbce_two_factor_t('placeholder_help',array(),'two_factor_email')).'</small></p><fieldset class="wide" data-email-template-fields><legend data-email-language-legend>'.$h($legend).'</legend><label>'.$h(wbce_two_factor_t('subject',array(),'two_factor_email')).'<input name="subject" value="'.$h($current['subject']).'" maxlength="190" required></label><label>'.$h(wbce_two_factor_t('message_template',array(),'two_factor_email')).'<textarea name="message" rows="5" required>'.$h($current['message']).'</textarea></label></fieldset><script type="application/json" data-email-language-templates>'.json_encode(array('templates'=>$templates,'names'=>$languages),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP).'</script>';
  $html.='<script>(function(script){var form=script.closest("form"),picker=form&&form.querySelector("[data-email-language-picker]"),source=form&&form.querySelector("[data-email-language-templates]"),subject=form&&form.querySelector("[name=subject]"),message=form&&form.querySelector("[name=message]"),legend=form&&form.querySelector("[data-email-language-legend]"),payload={templates:{},names:{}};if(!picker||!source||!subject||!message)return;try{payload=JSON.parse(source.textContent)}catch(ignore){}function show(){var code=picker.value,item=(payload.templates||{})[code]||{subject:"",message:""},name=(payload.names||{})[code]||code;subject.value=item.subject||"";message.value=item.message||"";if(legend)legend.textContent=name+" ("+code+")"}picker.addEventListener("change",show);if(window.jQuery)window.jQuery(picker).on("change select2:select",show);show()})(document.currentScript);</script>';
  return $html.'<button type="submit" class="button">'.$h(wbce_two_factor_t('save',array(),'two_factor_email')).'</button></form>';
 },
 'save_config'=>static function($input)use($database){$s=new WbceEmailFactorService($database);$languages=$s->installedLanguages();$target=strtoupper(trim((string)($input['target_language']??'')));if(!isset($languages[$target]))throw new RuntimeException(wbce_two_factor_t('language_invalid',array(),'two_factor_email'));$subject=trim((string)($input['subject']??''));$message=trim((string)($input['message']??''));if($subject===''||$message===''||strpos($message,'{code}')===false)throw new RuntimeException(wbce_two_factor_t('template_invalid',array(),'two_factor_email'));if(!$s->setSetting('subject.'.$target,$subject)||!$s->setSetting('message.'.$target,$message))throw new RuntimeException(wbce_two_factor_t('save_failed',array(),'two_factor_email'));$validity=(string)($input['validity']??'300');if(!in_array($validity,array('300','600'),true))$validity='300';if(!$s->setSetting('validity',$validity))throw new RuntimeException(wbce_two_factor_t('save_failed',array(),'two_factor_email'));}
));
if(!function_exists('wbce_add_filter')||!class_exists('WbceAuthFactorManager'))return;
require_once __DIR__.'/Provider.php';WbceAuthFactorManager::register(new WbceEmailFactorProvider($database));
if(class_exists('WbceTwoFactorCompatibility'))WbceTwoFactorCompatibility::enforce();
