<?php
require_once WB_PATH.'/modules/two_factor/Language.php';
final class WbceEmailFactorService
{
 private $db;
 public function __construct($database){if(!is_object($database)||!method_exists($database,'query'))throw new RuntimeException(wbce_two_factor_t('database_unavailable',array(),'two_factor_email'));$this->db=$database;}
 public static function install($db){if(!is_object($db)||!method_exists($db,'query'))return false;$a=$db->query("CREATE TABLE IF NOT EXISTS `{TP}mod_two_factor_email_settings` (`name` varchar(80) NOT NULL,`value` text NOT NULL,PRIMARY KEY(`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$b=$db->query("CREATE TABLE IF NOT EXISTS `{TP}mod_two_factor_email_users` (`user_id` int NOT NULL,`enabled` tinyint(1) NOT NULL DEFAULT 0,`confirmed_at` int DEFAULT NULL,PRIMARY KEY(`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$c=$db->query("CREATE TABLE IF NOT EXISTS `{TP}mod_two_factor_email_codes` (`user_id` int NOT NULL,`code_hash` varchar(255) NOT NULL,`expires_at` int NOT NULL,`attempts` int NOT NULL DEFAULT 0,`sent_at` int NOT NULL,PRIMARY KEY(`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");return(bool)($a&&$b&&$c);}
 private function esc($value){return $this->db->escapeString((string)$value);}
 public function setting($name,$default=''){$r=$this->db->query("SELECT `value` FROM `{TP}mod_two_factor_email_settings` WHERE `name`='".$this->esc($name)."' LIMIT 1");$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;return $row?(string)$row['value']:(string)$default;}
 public function setSetting($name,$value){return(bool)$this->db->query("INSERT INTO `{TP}mod_two_factor_email_settings` (`name`,`value`) VALUES ('".$this->esc($name)."','".$this->esc($value)."') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)");}
 public function installedLanguages(){$languages=array();$r=$this->db->query("SELECT `directory`,`name` FROM `{TP}addons` WHERE `type`='language' ORDER BY `name`");while($r&&($row=$r->fetchRow(MYSQLI_ASSOC))){$code=strtoupper((string)$row['directory']);if(preg_match('/^[A-Z]{2}$/',$code))$languages[$code]=(string)$row['name'];}if(!$languages)$languages=array('DE'=>'Deutsch','EN'=>'English');return $languages;}
 public function userLanguage($uid){$r=$this->db->query('SELECT `language` FROM `{TP}users` WHERE `user_id`='.(int)$uid.' LIMIT 1');$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;$code=strtoupper((string)($row['language']??''));return preg_match('/^[A-Z]{2}$/',$code)?$code:(defined('DEFAULT_LANGUAGE')?strtoupper((string)DEFAULT_LANGUAGE):'EN');}
 public function localizedSetting($name,$language,$default=''){$language=strtoupper((string)$language);$value=$this->setting($name.'.'.$language,'');if($value!=='')return $value;$fallback=defined('DEFAULT_LANGUAGE')?strtoupper((string)DEFAULT_LANGUAGE):'EN';if($fallback!==$language&&($value=$this->setting($name.'.'.$fallback,''))!=='')return $value;if($language!=='EN'&&($value=$this->setting($name.'.EN',''))!=='')return $value;$legacy=$this->setting($name,'');return $legacy!==''?$legacy:$default;}
 public function textForLanguage($key,$language){$language=strtoupper((string)$language);$path=__DIR__.'/languages/'.(is_file(__DIR__.'/languages/'.$language.'.php')?$language:'EN').'.php';$texts=(array)require $path;return isset($texts[$key])?(string)$texts[$key]:(string)$key;}
 public function isConfigured(){
  $registry=WB_PATH.'/modules/mailer/src/MailerRegistry.php';
  if(!is_file($registry))return false;
  try{require_once $registry;return class_exists('WbceMailerRegistry')&&WbceMailerRegistry::isReady();}catch(Throwable $ignored){return false;}
 }
 public function isEnabled($uid){$r=$this->db->query('SELECT `enabled` FROM `{TP}mod_two_factor_email_users` WHERE `user_id`='.(int)$uid);$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;return $row&&!empty($row['enabled']);}
 public function usage(){$r=$this->db->query('SELECT COUNT(*) AS amount FROM `{TP}mod_two_factor_email_users` WHERE `enabled`=1');$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;return $row?(int)$row['amount']:0;}
 public function userEmail($uid){$r=$this->db->query('SELECT `email` FROM `{TP}users` WHERE `user_id`='.(int)$uid.' LIMIT 1');$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;$email=$row?(string)$row['email']:'';return filter_var($email,FILTER_VALIDATE_EMAIL)?$email:'';}
 public function maskedEmail($uid){$email=$this->userEmail($uid);if($email==='')return '';$parts=explode('@',$email,2);$name=$parts[0];$length=function_exists('mb_strlen')?mb_strlen($name,'UTF-8'):strlen($name);$first=function_exists('mb_substr')?mb_substr($name,0,1,'UTF-8'):substr($name,0,1);return $first.str_repeat('*',max(2,$length-1)).'@'.$parts[1];}
 public function sendCode($uid,$force=false){if(!$this->isConfigured())throw new RuntimeException(wbce_two_factor_t('not_configured',array(),'two_factor_email'));$email=$this->userEmail($uid);if($email==='')throw new RuntimeException(wbce_two_factor_t('email_missing',array(),'two_factor_email'));$now=time();$r=$this->db->query('SELECT `expires_at`,`sent_at` FROM `{TP}mod_two_factor_email_codes` WHERE `user_id`='.(int)$uid);$old=$r?$r->fetchRow(MYSQLI_ASSOC):null;if(!$force&&$old&&(int)$old['expires_at']>$now&&(int)$old['sent_at']>$now-60)return;$code=(string)random_int(100000,999999);$this->deliver($email,$code,$uid);$hash=password_hash($code,PASSWORD_DEFAULT);$validity=(int)$this->setting('validity','300');if(!in_array($validity,array(300,600),true))$validity=300;$this->db->query("INSERT INTO `{TP}mod_two_factor_email_codes` (`user_id`,`code_hash`,`expires_at`,`attempts`,`sent_at`) VALUES (".(int)$uid.",'".$this->esc($hash)."',".($now+$validity).",0,$now) ON DUPLICATE KEY UPDATE `code_hash`=VALUES(`code_hash`),`expires_at`=VALUES(`expires_at`),`attempts`=0,`sent_at`=VALUES(`sent_at`)");}
 private function deliver($email,$code,$uid){if(!class_exists('Mailer')){if(is_file(WB_PATH.'/framework/Mailer.php'))require_once WB_PATH.'/framework/Mailer.php';elseif(is_file(WB_PATH.'/framework/class.wbmailer.php'))require_once WB_PATH.'/framework/class.wbmailer.php';}$class=class_exists('Mailer')?'Mailer':(class_exists('wbmailer')?'wbmailer':'');if($class==='')throw new RuntimeException(wbce_two_factor_t('mailer_missing',array(),'two_factor_email'));$language=$this->userLanguage((int)$uid);$validity=(int)$this->setting('validity','300');$minutes=(string)max(1,(int)ceil($validity/60));$subject=$this->localizedSetting('subject',$language,$this->textForLanguage('default_subject',$language));$body=str_replace(array('{code}','{site}','{minutes}'),array($code,defined('WEBSITE_TITLE')?WEBSITE_TITLE:WB_URL,$minutes),$this->localizedSetting('message',$language,$this->textForLanguage('default_message',$language)));$mail=new $class();$mail->AddAddress($email);$mail->Subject=preg_replace('/[\r\n]+/',' ',$subject);$mail->Body=nl2br(htmlspecialchars($body,ENT_QUOTES,'UTF-8'));$mail->AltBody=$body;if(!$mail->Send())throw new RuntimeException(wbce_two_factor_t('delivery_failed',array(),'two_factor_email'));}
 public function verify($uid,$code,$activate=false){$uid=(int)$uid;$code=trim((string)$code);$r=$this->db->query('SELECT `code_hash`,`expires_at`,`attempts` FROM `{TP}mod_two_factor_email_codes` WHERE `user_id`='.$uid);$row=$r?$r->fetchRow(MYSQLI_ASSOC):null;if(!$row)return false;if((int)$row['expires_at']<time()||(int)$row['attempts']>=5){$this->db->query('DELETE FROM `{TP}mod_two_factor_email_codes` WHERE `user_id`='.$uid);return false;}if(!preg_match('/^[0-9]{6}$/',$code))return false;$this->db->query('UPDATE `{TP}mod_two_factor_email_codes` SET `attempts`=`attempts`+1 WHERE `user_id`='.$uid);if(!password_verify($code,$row['code_hash']))return false;$this->db->query('DELETE FROM `{TP}mod_two_factor_email_codes` WHERE `user_id`='.$uid);if($activate){$this->db->query("INSERT INTO `{TP}mod_two_factor_email_users` (`user_id`,`enabled`,`confirmed_at`) VALUES (".$uid.",1,".time().") ON DUPLICATE KEY UPDATE `enabled`=1,`confirmed_at`=VALUES(`confirmed_at`)");require_once WB_PATH.'/modules/two_factor/Settings.php';WbceTwoFactorSettings::setUserProvider($this->db,$uid,'email');}return true;}
 public function disable($uid){$this->db->query('DELETE FROM `{TP}mod_two_factor_email_codes` WHERE `user_id`='.(int)$uid);$this->db->query('DELETE FROM `{TP}mod_two_factor_email_users` WHERE `user_id`='.(int)$uid);require_once WB_PATH.'/modules/two_factor/Settings.php';if(WbceTwoFactorSettings::userProvider($this->db,$uid)==='email')WbceTwoFactorSettings::setUserProvider($this->db,$uid,'');}
}
