<?php
$workerLanguageTexts = array(
'module_name'=>'Worker','module_description'=>'Cron-kompatible Aufgabenplanung und asynchrone Worker-Ausführung für WBCE-Module.',
'settings_security'=>'Sicherheitsprüfung fehlgeschlagen.','settings_saved'=>'Worker-Betriebsart wurde gespeichert.','token_renewed'=>'Der URL-Token wurde erneuert. Die bisherige URL ist ab sofort ungültig.',
'invalid_mode'=>'Ungültige Worker-Betriebsart.','invalid_interval'=>'Ungültiges Cron-Intervall.','invalid_token'=>'Ungültiger Worker-Token.',
'heartbeat_skipped'=>'Aufruf protokolliert; Ausführung durch Seitencron-Intervall begrenzt.','heartbeat_success'=>'Haupt-Cron erfolgreich aufgerufen.',
'cron_diagnostics'=>'Cron-Diagnose','source'=>'Quelle','finished'=>'Beendet','last_phase'=>'Letzte erreichte Phase','started_tasks'=>'Gestartete Aufgaben','trace_received'=>'Website-Cron angenommen.','trace_due'=>'Fällige Aufgaben werden ermittelt.','trace_claim'=>'Aufgabe #{id} ({worker}) wird gesperrt.','trace_launch'=>'Aufgabe #{id} ({worker}) wird intern gestartet.',
'hero_kicker'=>'AUTOMATISIERUNG','hero_text'=>'Zeitgesteuerte Aufgaben zentral verwalten und getrennt im Hintergrund ausführen.','new_task'=>'Neue Aufgabe',
'last_call'=>'Letzter Aufruf des Haupt-Crons:','never_called'=>'Noch kein Aufruf registriert','warning'=>'Warnung: Der Haupt-Cron wurde nicht innerhalb des eingestellten Intervalls von {minutes} {unit} aufgerufen und ist möglicherweise nicht richtig eingerichtet.','heartbeat_ok'=>'Der Haupt-Cron wird innerhalb des eingestellten Intervalls aufgerufen.',
'execution'=>'Ausführung','mode_cron'=>'Echter Cron','mode_cron_help'=>'Aufruf über den System-Cron.','mode_url'=>'URL-Cron','mode_url_help'=>'Aufruf durch einen externen Cron-Dienst.','mode_pageview'=>'Seitenaufruf','mode_pageview_help'=>'Aufruf durch Frontend-Seitenzugriffe.','interval'=>'Intervall','minute'=>'Minute','minutes'=>'Minuten','save_selection'=>'Auswahl speichern','max_tasks_per_run'=>'Maximale Aufgaben pro Lauf','run_budget_seconds'=>'Laufzeitbudget je Durchlauf (Sekunden)','pause_between_tasks_ms'=>'Pause zwischen Aufgaben (ms)','runtime_limits_help'=>'Begrenzt parallele Hintergrundstarts und die Dauer eines Scheduler-Durchlaufs. Der Cron-Befehl verwendet zusätzlich eine niedrige CPU-Priorität.','invalid_limits'=>'Die Laufzeitbegrenzungen liegen außerhalb des erlaubten Bereichs.',
'system_cron'=>'System-Cron alle {minutes} {unit}','url_cron'=>'Geschützte Cron-URL – alle {minutes} {unit} aufrufen','copy'=>'kopieren','renew_token'=>'URL-Token erneuern','pageview_hint'=>'Im Modus „Seitenaufruf“ prüfen Frontend-Aufrufe den Worker. Eine tatsächliche Ausführung erfolgt höchstens alle {minutes} {unit}. System-Cron und Webcron-URL sind deaktiviert.',
'loading'=>'Aufgaben werden geladen …','task'=>'AUFGABE','close'=>'Schließen','name'=>'Name','worker'=>'Worker','cron_schema'=>'Cron-Schema','cron_help'=>'Minute · Stunde · Tag · Monat · Wochentag','configuration'=>'Konfiguration (JSON)','activate_task'=>'Aufgabe aktivieren','cancel'=>'Abbrechen','save'=>'Speichern','confirm'=>'Bestätigen','processing'=>'Wird ausgeführt …',
'all'=>'Alle','registered'=>'REGISTRIERT','registered_workers'=>'Registrierte Worker','no_workers'=>'Keine Worker registriert.','scheduled_tasks'=>'Geplante Aufgaben','no_tasks'=>'Noch keine Aufgaben angelegt.','last_runs'=>'Letzte Ausführungen','start'=>'Start','status'=>'Status','message'=>'Meldung','duration'=>'Dauer','no_runs'=>'Noch keine Ausführungen.',
'running'=>'läuft','ready'=>'bereit','successful'=>'erfolgreich','failed'=>'fehlgeschlagen','skipped'=>'übersprungen','never'=>'noch nie','task_singular'=>'Aufgabe','task_plural'=>'Aufgaben','worker_missing'=>'Der registrierte Worker ist derzeit nicht installiert.','managed'=>'Automatisch verwaltet','managed_task'=>'Automatisch verwaltete Aufgaben können hier nicht geändert werden.','toggle'=>'Aktivieren/deaktivieren','next_run'=>'Nächster Lauf:','run_now'=>'Jetzt ausführen','edit'=>'Bearbeiten','delete'=>'Löschen',
'active_schedules'=>'aktive Zeitpläne','no_active_schedule'=>'Kein aktiver Zeitplan',
'copied'=>'Angabe kopiert.','launched'=>'Aufgabe wurde im Hintergrund gestartet.','delete_confirm'=>'Aufgabe und ihre Protokolle wirklich löschen?','task_deleted'=>'Aufgabe gelöscht.','status_saved'=>'Status gespeichert.','task_saved'=>'Aufgabe gespeichert.','settings_updated'=>'Einstellungen gespeichert.','settings_load_error'=>'Die aktualisierte Ansicht konnte nicht geladen werden.','settings_save_error'=>'Einstellungen konnten nicht gespeichert werden.','token_confirm'=>'Token wirklich erneuern? Die bisherige Webcron-URL wird sofort ungültig.','request_failed'=>'Anfrage fehlgeschlagen.','edit_task'=>'Aufgabe bearbeiten','permission_denied'=>'Keine Berechtigung.','task_completed'=>'Aufgabe erfolgreich abgeschlossen.','invalid_arguments'=>'Ungültige Worker-Argumente.',
'cleanup_label'=>'Worker-Protokolle bereinigen','cleanup_description'=>'Entfernt alte Ausführungsprotokolle. Konfiguration: {"days":30}','cleanup_done'=>'Alte Worker-Protokolle wurden bereinigt.',
'invalid_name'=>'Bitte einen gültigen Namen angeben.','worker_unavailable'=>'Der ausgewählte Worker ist nicht verfügbar.','json_invalid'=>'Die Konfiguration muss ein gültiges JSON-Objekt sein.','task_not_found'=>'Aufgabe nicht gefunden.','lock_invalid'=>'Ungültige oder abgelaufene Worker-Sperre.','registered_unavailable'=>'Der registrierte Worker ist nicht verfügbar.','security_expired'=>'Die Sicherheitsprüfung ist abgelaufen. Bitte die Seite neu öffnen.','already_running'=>'Die Aufgabe läuft bereits oder wurde nicht gefunden.','unknown_action'=>'Unbekannte Aktion.','async_disabled'=>'Asynchrone Systemprozesse sind nicht verfügbar; die Aufgabe wird direkt ausgeführt.','background_failed'=>'Der Hintergrundprozess konnte nicht gestartet werden.',
'cron_five_fields'=>'Ein Cron-Ausdruck benötigt fünf Felder.','cron_no_date'=>'Innerhalb von fünf Jahren wurde kein Ausführungszeitpunkt gefunden.','cron_invalid_field'=>'Ungültiges Cron-Feld: ','cron_out_of_range'=>'Cron-Wert außerhalb des erlaubten Bereichs: '
,'internal_address_invalid'=>'Die interne Worker-Adresse ist ungültig.','internal_secret_missing'=>'Der interne Worker-Schlüssel fehlt.','async_connect_failed'=>'Asynchroner Worker-Aufruf nicht möglich: {error}','connection_failed'=>'Verbindung fehlgeschlagen','async_request_incomplete'=>'Der asynchrone Worker-Aufruf konnte nicht vollständig versendet werden.','task_id_unresolved'=>'Die ID der neuen Worker-Aufgabe konnte nicht ermittelt werden.','running_delete_denied'=>'Die Aufgabe wird gerade ausgeführt und kann erst danach gelöscht werden.','log_id_unresolved'=>'Der Worker-Protokolleintrag konnte nicht angelegt werden.','stale_lock_released'=>'Eine hängen gebliebene asynchrone Ausführung wurde nach 24 Stunden freigegeben.'
,'post_required'=>'Änderungen sind nur über eine sichere Formularanfrage erlaubt.','database_write_failed'=>'Die Änderung konnte nicht in der Datenbank gespeichert werden.','secure_token_failed'=>'Die sichere Worker-Freigabe konnte nicht erzeugt werden.','database_unavailable'=>'Die Worker-Datenbank ist nicht verfügbar.'
);
