<?php
$workerLanguageTexts = array(
'module_name'=>'Worker','module_description'=>'Cron-compatible scheduler and asynchronous worker runner for WBCE modules.',
'settings_security'=>'Security check failed.','settings_saved'=>'Worker trigger mode was saved.','token_renewed'=>'The URL token was renewed. The previous URL is now invalid.',
'invalid_mode'=>'Invalid worker trigger mode.','invalid_interval'=>'Invalid cron interval.','invalid_token'=>'Invalid worker token.',
'heartbeat_skipped'=>'Call logged; execution limited by the page-cron interval.','heartbeat_success'=>'Main cron called successfully.',
'cron_diagnostics'=>'Cron diagnostics','source'=>'Source','finished'=>'Finished','last_phase'=>'Last reached phase','started_tasks'=>'Started tasks','trace_received'=>'Website cron accepted.','trace_due'=>'Looking up due tasks.','trace_claim'=>'Claiming task #{id} ({worker}).','trace_launch'=>'Launching task #{id} ({worker}) internally.',
'hero_kicker'=>'AUTOMATION','hero_text'=>'Manage scheduled tasks centrally and run them separately in the background.','new_task'=>'New task',
'last_call'=>'Last main-cron call:','never_called'=>'No call registered yet','warning'=>'Warning: The main cron was not called within the configured interval of {minutes} {unit} and may not be configured correctly.','heartbeat_ok'=>'The main cron is called within the configured interval.',
'execution'=>'Execution','mode_cron'=>'Real cron','mode_cron_help'=>'Triggered by the system cron.','mode_url'=>'URL cron','mode_url_help'=>'Triggered by an external cron service.','mode_pageview'=>'Page view','mode_pageview_help'=>'Triggered by frontend page views.','interval'=>'Interval','minute'=>'minute','minutes'=>'minutes','save_selection'=>'Save selection','max_tasks_per_run'=>'Maximum tasks per run','run_budget_seconds'=>'Run time budget (seconds)','pause_between_tasks_ms'=>'Pause between tasks (ms)','runtime_limits_help'=>'Limits parallel background starts and the duration of one scheduler run. The cron command also uses a low CPU priority.','invalid_limits'=>'The runtime limits are outside the permitted range.',
'system_cron'=>'System cron every {minutes} {unit}','url_cron'=>'Protected cron URL — call every {minutes} {unit}','copy'=>'Copy','renew_token'=>'Renew URL token','pageview_hint'=>'In page-view mode, frontend requests check the worker. Actual execution occurs at most every {minutes} {unit}. System cron and URL cron are disabled.',
'loading'=>'Loading tasks…','task'=>'TASK','close'=>'Close','name'=>'Name','worker'=>'Worker','cron_schema'=>'Cron expression','cron_help'=>'Minute · Hour · Day · Month · Weekday','configuration'=>'Configuration (JSON)','activate_task'=>'Activate task','cancel'=>'Cancel','save'=>'Save','confirm'=>'Confirm','processing'=>'Processing …',
'all'=>'All','registered'=>'REGISTERED','registered_workers'=>'Registered workers','no_workers'=>'No workers registered.','scheduled_tasks'=>'Scheduled tasks','no_tasks'=>'No tasks created yet.','last_runs'=>'Recent executions','start'=>'Start','status'=>'Status','message'=>'Message','duration'=>'Duration','no_runs'=>'No executions yet.',
'running'=>'running','ready'=>'ready','successful'=>'successful','failed'=>'failed','skipped'=>'skipped','never'=>'never','task_singular'=>'task','task_plural'=>'tasks','worker_missing'=>'The registered worker is currently not installed.','managed'=>'Managed automatically','managed_task'=>'Automatically managed tasks cannot be changed here.','toggle'=>'Enable/disable','next_run'=>'Next run:','run_now'=>'Run now','edit'=>'Edit','delete'=>'Delete',
'active_schedules'=>'active schedules','no_active_schedule'=>'No active schedule',
'copied'=>'Value copied.','launched'=>'Task started in the background.','delete_confirm'=>'Really delete the task and its logs?','task_deleted'=>'Task deleted.','status_saved'=>'Status saved.','task_saved'=>'Task saved.','settings_updated'=>'Settings saved.','settings_load_error'=>'The updated view could not be loaded.','settings_save_error'=>'Settings could not be saved.','token_confirm'=>'Renew token? The previous webcron URL will become invalid immediately.','request_failed'=>'Request failed.','edit_task'=>'Edit task','permission_denied'=>'Permission denied.','task_completed'=>'Task completed successfully.','invalid_arguments'=>'Invalid worker arguments.',
'cleanup_label'=>'Clean worker logs','cleanup_description'=>'Removes old execution logs. Configuration: {"days":30}','cleanup_done'=>'Old worker logs were removed.',
'invalid_name'=>'Please enter a valid name.','worker_unavailable'=>'The selected worker is not available.','json_invalid'=>'Configuration must be a valid JSON object.','task_not_found'=>'Task not found.','lock_invalid'=>'Invalid or expired worker lock.','registered_unavailable'=>'The registered worker is not available.','security_expired'=>'The security check expired. Please reload the page.','already_running'=>'The task is already running or was not found.','unknown_action'=>'Unknown action.','async_disabled'=>'Asynchronous system processes are unavailable; the task will run directly.','background_failed'=>'The background process could not be started.',
'cron_five_fields'=>'A cron expression requires five fields.','cron_no_date'=>'No execution time was found within five years.','cron_invalid_field'=>'Invalid cron field: ','cron_out_of_range'=>'Cron value outside the allowed range: '
,'internal_address_invalid'=>'The internal worker address is invalid.','internal_secret_missing'=>'The internal worker secret is missing.','async_connect_failed'=>'Asynchronous worker request unavailable: {error}','connection_failed'=>'Connection failed','async_request_incomplete'=>'The asynchronous worker request could not be sent completely.','task_id_unresolved'=>'The new worker task ID could not be determined.','running_delete_denied'=>'The task is currently running and can only be deleted afterwards.','log_id_unresolved'=>'The worker log entry could not be created.','stale_lock_released'=>'A stalled asynchronous execution was released after 24 hours.'
,'post_required'=>'Changes are only allowed through a secure form request.','database_write_failed'=>'The change could not be saved to the database.','secure_token_failed'=>'The secure worker authorization could not be generated.','database_unavailable'=>'The worker database is unavailable.'
);
