<?php

defined('WB_PATH') && isset($admin) or die('Access denied');
require_once __DIR__.'/src/MailerRegistry.php';
require_once __DIR__.'/src/I18n.php';
$t=static fn(string $key,string $fallback='')=>WbceMailerI18n::t($key,$fallback);
$s=WbceMailerRegistry::settings(); $p=WbceMailerRegistry::providers(); $mailerStatus=WbceMailerRegistry::configurationState(); $statusKey=['ok'=>'STATUS_OK','error'=>'STATUS_ERROR','temporary_error'=>'STATUS_TEMPORARY_ERROR','unconfigured'=>'STATUS_UNCONFIGURED'][$mailerStatus]??'STATUS_UNCONFIGURED';
$provider=isset($p[$s['provider']??''])?(string)$s['provider']:'smtp';
$transports=(array)($p[$provider]['transports']??['smtp']);
$transport=(string)($s['provider_transport']??reset($transports)); if(!in_array($transport,$transports,true))$transport=(string)reset($transports);
$prefix=$provider==='smtp'?'mailer_smtp_':'mailer_'.$provider.'_smtp_';
$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$apiSchemas=[];$smtpSchemas=[];$smtpValues=[];$apiValues=[];
foreach($p as $id=>$definition){
    $apiSchemas[$id]=array_map(static function(array $field):array{$field['label']=WbceMailerI18n::label((string)($field['label']??''));return $field;},(array)($definition['api_fields']??[]));
    $smtpSchemas[$id]=(array)($definition['smtp']??[]);
    $providerPrefix=$id==='smtp'?'mailer_smtp_':'mailer_'.$id.'_smtp_';
    $smtpValues[$id]=array('username'=>(string)Settings::get($providerPrefix.'username',''),'host'=>(string)Settings::get($providerPrefix.'host',''),'port'=>(string)Settings::get($providerPrefix.'port','587'),'encryption'=>(string)Settings::get($providerPrefix.'encryption','tls'),'region'=>(string)Settings::get($providerPrefix.'region',''));
    $apiValues[$id]=array(); foreach((array)($definition['api_fields']??[]) as $field){$name=(string)($field['name']??'');if($name!=='')$apiValues[$id][$name]=(string)Settings::get('mailer_'.$id.'_api_'.$name,'');}
}
?>
<link rel="stylesheet" href="<?= $h(WB_URL.'/modules/cookie_banner/assets/admin.css') ?>">
<style>
.mailer-topline{align-items:center;display:flex;justify-content:space-between;gap:16px}.mailer-status{align-items:center;border-radius:12px;color:#fff;display:flex;font-size:12px;font-weight:700;gap:6px;padding:6px 9px}.mailer-status:before{background:currentColor;border:2px solid rgba(255,255,255,.75);border-radius:50%;content:'';height:7px;width:7px}.mailer-status--ok{background:#36a85a}.mailer-status--error{background:#b3261e}.mailer-status--temporary_error{background:#a66f00}.mailer-status--unconfigured{background:#b8c1cb;color:#263238}.mailer-status--unconfigured:before{border-color:rgba(38,50,56,.5)}.mailer-choices{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin:12px 0 20px}.mailer-choice{outline:0}.mailer-choice,.mailer-choice:hover,.mailer-choice:focus,.mailer-choice:active,.mailer-choice.is-selected{appearance:none;background:#fff!important;background-color:#fff!important;background-image:none!important;color:#111!important;border:2px solid var(--wbce-admin-border,#d7e0e8)!important;border-radius:10px;box-shadow:none!important;cursor:pointer;box-sizing:border-box;display:flex;flex-direction:column;height:164px;padding:17px;position:relative;text-align:left;transition:border-color .15s}.mailer-choice:hover,.mailer-choice:focus,.mailer-choice.is-selected{background:#fff!important;background-color:#fff!important;background-image:none!important;border-color:var(--wbce-admin-primary,#2271b1)!important;box-shadow:none!important}.mailer-choice.is-disabled,.mailer-choice.is-disabled:hover,.mailer-choice.is-disabled:focus{background:#fff!important;background-color:#fff!important;border-color:var(--wbce-admin-border,#d7e0e8)!important;cursor:not-allowed;opacity:.42}.mailer-choice i{color:#2271b1;font-size:22px;margin-right:10px}.mailer-choice strong{display:block;margin-top:10px}.mailer-choice small{color:#526371;display:block;margin-top:5px;line-height:1.35}.mailer-choice.is-selected:after{background:#36a85a;border-radius:10px;color:#fff;content:'<?= $h($t('ACTIVE')) ?>';font-size:10px;font-weight:700;line-height:1;margin:0;padding:4px 7px;position:absolute;right:10px;top:10px}.mailer-choice.is-disabled:after{content:'<?= $h($t('SYMFONY_ONLY')) ?>';display:block;font-size:12px;margin-top:10px}.mailer-choice.is-disabled.is-selected:after{content:'';display:none}.mailer-section-title{font-size:17px;margin:8px 0}.mailer-provider-form[hidden],.mailer-transport-block[hidden]{display:none}.cookie-save-block [name=test]{margin-right:auto}
</style>
<main class="cookie-banner-tool"><header class="cookie-banner-hero"><i class="fa fa-envelope"></i><div><h2><?= $h($t('TITLE','Mailer')) ?></h2><p><?= $h($t('INTRO')) ?></p></div></header>
<form class="cookie-banner-form" method="post" action="<?= $h(WB_URL.'/modules/mailer/api.php') ?>"><?= $admin->getFTAN() ?>
<input type="hidden" name="engine" value="<?= $h($s['engine']) ?>"><input type="hidden" name="provider" value="<?= $h($provider) ?>"><input type="hidden" name="provider_transport" value="<?= $h($transport) ?>">
<section class="cookie-banner-card"><div class="mailer-topline"><label class="cookie-banner-switch"><input type="checkbox" name="enabled" value="1"<?= $s['enabled']==='1'?' checked':'' ?>><span></span><?= $h($t('ENABLE')) ?></label><span class="mailer-status mailer-status--<?= $h($mailerStatus) ?>"><?= $h($t($statusKey)) ?></span></div><div class="cookie-banner-grid"><label><?= $h($t('FROM_EMAIL')) ?><input type="email" name="from_email" value="<?= $h($s['from_email']??'') ?>"></label><label><?= $h($t('FROM_NAME')) ?><input name="from_name" value="<?= $h($s['from_name']??'') ?>"></label></div>
<h3 class="mailer-section-title"><?= $h($t('ENGINE')) ?></h3><div class="mailer-choices"><?php foreach(['symfony'=>['fa fa-paper-plane','Symfony Mailer',$t('SYMFONY_DESC')],'phpmailer'=>['fa fa-envelope','PHPMailer',$t('PHPMAILER_DESC')]] as $id=>$v): ?><div class="mailer-choice" role="button" tabindex="0" data-engine="<?= $id ?>"><i class="<?= $v[0] ?>"></i><strong><?= $v[1] ?></strong><small><?= $v[2] ?></small></div><?php endforeach; ?></div>
<h3 class="mailer-section-title"><?= $h($t('PROVIDER')) ?></h3><div class="mailer-choices"><?php foreach($p as $id=>$v):if($id==='symfony')continue; ?><div class="mailer-choice" role="button" tabindex="0" data-provider="<?= $h($id) ?>" data-transports="<?= $h(implode(',',(array)($v['transports']??['smtp']))) ?>"><i class="<?= $h($v['icon']??'fa fa-envelope') ?>"></i><strong><?= $h($v['name']) ?></strong><small><?= $h($v['description']) ?></small></div><?php endforeach; ?></div></section>
<section class="cookie-banner-card mailer-transport-block" data-transport-block><h3 class="mailer-section-title"><?= $h($t('CONNECTION')) ?></h3><div class="mailer-choices"><div class="mailer-choice" role="button" tabindex="0" data-transport="api"><i class="fa fa-key"></i><strong><?= $h($t('API')) ?></strong><small><?= $h($t('API_DESC')) ?></small></div><div class="mailer-choice" role="button" tabindex="0" data-transport="smtp"><i class="fa fa-server"></i><strong><?= $h($t('SMTP')) ?></strong><small><?= $h($t('SMTP_DESC')) ?></small></div></div></section>
<section class="cookie-banner-card mailer-provider-form" data-smtp-form><h3><?= $h($t('SMTP_CONFIG')) ?></h3><div class="cookie-banner-grid"><label data-smtp-field="username"><?= $h($t('USERNAME')) ?><input name="smtp_username" value="<?= $h((string)Settings::get($prefix.'username','')) ?>"></label><label data-smtp-field="password"><?= $h($t('PASSWORD')) ?><input type="password" name="smtp_password" autocomplete="new-password" placeholder="<?= $h($t('KEEP_PASSWORD')) ?>"></label><label data-smtp-field="host"><?= $h($t('HOST')) ?><input name="smtp_host" value="<?= $h((string)Settings::get($prefix.'host','')) ?>" placeholder="smtp.example.org"></label><label data-smtp-field="port"><?= $h($t('PORT')) ?><input type="number" name="smtp_port" list="mailer-smtp-ports" min="1" max="65535" value="<?= $h((string)Settings::get($prefix.'port','587')) ?>"><datalist id="mailer-smtp-ports"><option value="25"><option value="465"><option value="587"><option value="2525"></datalist></label><label data-smtp-field="encryption"><?= $h($t('PROTOCOL')) ?><select name="smtp_encryption"><option value="tls"<?= Settings::get($prefix.'encryption','tls')==='tls'?' selected':'' ?>>STARTTLS</option><option value="ssl"<?= Settings::get($prefix.'encryption','tls')==='ssl'?' selected':'' ?>>SSL/TLS</option><option value=""<?= Settings::get($prefix.'encryption','tls')===''?' selected':'' ?>>Keine</option></select></label></div></section>
<section class="cookie-banner-card mailer-provider-form" data-api-form><h3 data-provider-title><?= $h($t('API_CONFIG')) ?></h3><div class="cookie-banner-grid" data-api-fields></div></section>
<section class="cookie-banner-card"><h3><?= $h($t('TEST')) ?></h3><div class="cookie-banner-grid"><label><?= $h($t('TEST_TO')) ?><input type="email" name="test_to" placeholder="mail@example.org"></label></div></section><section class="cookie-banner-card cookie-save-block"><button class="button" name="test" value="1"><?= $h($t('TEST_SEND')) ?></button><button class="button"><?= $h($t('SAVE')) ?></button></section></form><div class="cookie-banner-toast"></div></main>
<script>(function(){
document.querySelectorAll('.mailer-choice').forEach(function(choice){choice.onkeydown=function(event){if(choice.classList.contains('is-disabled'))return;if(event.key==='Enter'||event.key===' '){event.preventDefault();choice.click()}}});var f=document.querySelector('.cookie-banner-form'),toast=document.querySelector('.cookie-banner-toast'),engine=f.querySelector('[name=engine]'),provider=f.querySelector('[name=provider]'),transport=f.querySelector('[name=provider_transport]'),schemas=<?= json_encode($apiSchemas,JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_TAG) ?>,smtpSchemas=<?= json_encode($smtpSchemas,JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_TAG) ?>,smtpValues=<?= json_encode($smtpValues,JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_TAG) ?>,apiValues=<?= json_encode($apiValues,JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_TAG) ?>;
function renderApiFields(){var box=f.querySelector('[data-api-fields]');box.innerHTML='';(schemas[provider.value]||[]).forEach(function(def){var label=document.createElement('label'),caption=document.createElement('span'),input=document.createElement('input'),saved=((apiValues[provider.value]||{})[def.name]||'');caption.textContent=def.label;input.name='api_'+def.name;input.type=def.type||'text';input.required=!!def.required;input.autocomplete=def.type==='password'?'new-password':'off';input.placeholder=saved&&input.type==='password'?'<?= $h($t('KEEP_PASSWORD')) ?>':(def.placeholder||'');if(def.options&&def.options.length){var select=document.createElement('select');select.name=input.name;select.required=input.required;def.options.forEach(function(value){var option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===saved;select.append(option)});label.append(caption,select)}else{if(input.type!=='password')input.value=saved;label.append(caption,input)}box.append(label)})}
function renderSmtpFields(){var profile=smtpSchemas[provider.value]||{},saved=smtpValues[provider.value]||{},grid=f.querySelector('[data-smtp-form] .cookie-banner-grid');grid.querySelectorAll('[data-smtp-dynamic]').forEach(function(node){node.remove()});if(profile.smtp_servers&&profile.smtp_servers.length){var label=document.createElement('label'),caption=document.createElement('span'),select=document.createElement('select');label.dataset.smtpDynamic='server';caption.textContent='<?= $h($t('SMTP_SERVER')) ?>';select.name='smtp_host';profile.smtp_servers.forEach(function(server){var option=document.createElement('option');option.value=server.value;option.textContent=server.label+' · '+server.value;option.selected=server.value===(saved.host||server.value);select.append(option)});label.append(caption,select);grid.insertBefore(label,grid.querySelector('[data-smtp-field=host]'));}if(profile.smtp_connections&&profile.smtp_connections.length){var connectionLabel=document.createElement('label'),connectionCaption=document.createElement('span'),connectionSelect=document.createElement('select');connectionLabel.dataset.smtpDynamic='connection';connectionCaption.textContent='<?= $h($t('CONNECTION')) ?>';connectionSelect.name='smtp_connection';profile.smtp_connections.forEach(function(connection){var option=document.createElement('option');option.value=connection.id;option.textContent=connection.label;option.selected=String(connection.port)===String(saved.port||'587')&&String(connection.encryption)===String(saved.encryption||'tls');connectionSelect.append(option)});connectionLabel.append(connectionCaption,connectionSelect);grid.insertBefore(connectionLabel,grid.querySelector('[data-smtp-field=port]'));}['username','host','port','encryption'].forEach(function(key){var input=f.querySelector('[name=smtp_'+key+']'),row=f.querySelector('[data-smtp-field='+key+']');if(!input||!row)return;var fixed=Object.prototype.hasOwnProperty.call(profile,key),byConnection=(key==='port'||key==='encryption')&&profile.smtp_connections&&profile.smtp_connections.length;row.hidden=fixed||byConnection||(key==='host'&&profile.smtp_servers&&profile.smtp_servers.length);input.readOnly=fixed;input.value=fixed?String(profile[key]):String(saved[key]||(key==='port'?'587':key==='encryption'?'tls':''));});var password=f.querySelector('[name=smtp_password]');if(password)password.value='';}
function providerMatchesEngine(tile){var routes=tile.dataset.transports.split(',');return engine.value==='phpmailer'?routes.indexOf('smtp')>=0:routes.some(function(route){return route==='smtp'||route==='api'})}
function sync(){var tiles=[].slice.call(document.querySelectorAll('[data-provider]')),tile=document.querySelector('[data-provider="'+provider.value+'"]');if(!tile||!providerMatchesEngine(tile)){tile=tiles.find(providerMatchesEngine)||document.querySelector('[data-provider="smtp"]');provider.value=tile?tile.dataset.provider:'smtp'}var supported=tile.dataset.transports.split(',');if(engine.value==='phpmailer')transport.value='smtp';if(supported.indexOf(transport.value)<0)transport.value=supported[0];document.querySelectorAll('[data-engine]').forEach(function(x){x.classList.toggle('is-selected',x.dataset.engine===engine.value)});tiles.forEach(function(x){var matches=providerMatchesEngine(x);x.hidden=!matches;x.classList.remove('is-disabled');x.setAttribute('aria-disabled','false');x.classList.toggle('is-selected',matches&&x.dataset.provider===provider.value)});document.querySelectorAll('[data-transport]').forEach(function(x){var off=supported.indexOf(x.dataset.transport)<0||(engine.value==='phpmailer'&&x.dataset.transport==='api');x.hidden=off;x.classList.toggle('is-disabled',off);x.setAttribute('aria-disabled',off?'true':'false');x.classList.toggle('is-selected',!off&&x.dataset.transport===transport.value)});f.querySelector('[data-transport-block]').hidden=supported.length<2;f.querySelector('[data-smtp-form]').hidden=transport.value!=='smtp';f.querySelector('[data-api-form]').hidden=transport.value!=='api';f.querySelector('[data-provider-title]').textContent=tile.querySelector('strong').textContent+' <?= $h($t('API_CONFIG')) ?>';renderApiFields();renderSmtpFields()}
document.querySelectorAll('[data-engine]').forEach(function(x){x.onclick=function(){engine.value=x.dataset.engine;sync()}});document.querySelectorAll('[data-provider]').forEach(function(x){x.onclick=function(){if(!x.classList.contains('is-disabled')){provider.value=x.dataset.provider;var routes=x.dataset.transports.split(',');transport.value=engine.value==='phpmailer'?'smtp':(routes.indexOf('api')>=0?'api':routes[0]);sync()}}});document.querySelectorAll('[data-transport]').forEach(function(x){x.onclick=function(){if(x.classList.contains('is-disabled'))return;transport.value=x.dataset.transport;sync()}});sync();f.onsubmit=function(e){e.preventDefault();fetch(f.action,{method:'POST',body:new FormData(f),credentials:'same-origin'}).then(function(r){return r.json()}).then(function(d){if(!d.ok)throw Error(d.message);toast.textContent=d.message;toast.className='cookie-banner-toast is-visible'}).catch(function(e){toast.textContent=e.message;toast.className='cookie-banner-toast is-visible is-error'})}})();</script>
