(function(){
 'use strict';
 function localizedUrl(root){var url=new URL(location.href);if(root&&root.dataset.language)url.searchParams.set('lang',root.dataset.language);return url.toString();}
 function showToast(root,message,error){var toast=root.querySelector('.log-center-toast');if(!toast)return;toast.hidden=false;toast.classList.toggle('error',!!error);toast.classList.toggle('wbce-admin-toast--error',!!error);toast.textContent=message;requestAnimationFrame(function(){toast.classList.add('is-visible');});window.clearTimeout(Number(toast.dataset.timer||0));toast.dataset.timer=String(window.setTimeout(function(){toast.classList.remove('is-visible');window.setTimeout(function(){toast.hidden=true;},180);},6500));}
 function bind(root){
  if(root.dataset.logCenterBound==='1')return;root.dataset.logCenterBound='1';
  var form=root.querySelector('[data-log-center-form]');if(!form)return;var initial=root.querySelector('.log-center-toast:not([hidden])');if(initial)showToast(root,initial.textContent,initial.classList.contains('error'));
  function submit(){
   var button=form.querySelector('button[type=submit]'),label=button.textContent,data=new FormData(form);
   Array.prototype.forEach.call(form.elements,function(el){el.disabled=true;});button.hidden=false;button.textContent=root.dataset.processing;
   fetch(localizedUrl(root),{method:'POST',body:data,credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest','Cache-Control':'no-cache'}})
    .then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text();})
    .then(function(html){var page=new DOMParser().parseFromString(html,'text/html'),next=page.querySelector('.log-center');if(!next)throw new Error('Invalid response');root.replaceWith(next);bind(next);})
    .catch(function(error){Array.prototype.forEach.call(form.elements,function(el){el.disabled=false;});button.textContent=label;showToast(root,error.message,true);});
  }
  form.addEventListener('submit',function(event){event.preventDefault();submit();});
  form.querySelectorAll('[data-log-center-service]').forEach(function(toggle){toggle.addEventListener('change',function(){
   var wanted=toggle.checked,card=toggle.closest('.log-center-service'),state=card.querySelector('[data-log-center-state]'),data=new FormData();
   form.querySelectorAll('input[type="hidden"]').forEach(function(input){if(input.name)data.append(input.name,input.value);});
   data.append('log_center_action','service');data.append('service_type',toggle.dataset.logCenterService);data.append('enabled',wanted?'1':'0');
   toggle.disabled=true;card.classList.add('is-processing');
   fetch(localizedUrl(root),{method:'POST',body:data,credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json','Cache-Control':'no-cache'}})
    .then(function(r){return r.text().then(function(body){var json;try{json=JSON.parse(body);}catch(e){throw new Error('HTTP '+r.status);}if(!r.ok)throw new Error('HTTP '+r.status);return json;});})
    .then(function(result){toggle.checked=!!result.enabled;state.textContent=toggle.checked?root.dataset.active:root.dataset.inactive;if(result.ftan){var box=document.createElement('div');box.innerHTML=result.ftan;form.querySelectorAll('input[type="hidden"]').forEach(function(input){input.remove();});Array.prototype.slice.call(box.children).reverse().forEach(function(node){form.insertBefore(node,form.firstChild);});}showToast(root,result.message,!result.ok);})
    .catch(function(error){toggle.checked=!wanted;showToast(root,error.message,true);})
    .finally(function(){toggle.disabled=false;card.classList.remove('is-processing');});
  });});
  var connectionToggle=form.querySelector('[data-log-center-connection]');if(connectionToggle)connectionToggle.addEventListener('change',function(){var wanted=connectionToggle.checked,data=new FormData();form.querySelectorAll('input[type="hidden"]').forEach(function(input){if(input.name)data.append(input.name,input.value);});data.append('log_center_action','connection');data.append('enabled',wanted?'1':'0');connectionToggle.disabled=true;fetch(localizedUrl(root),{method:'POST',body:data,credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(function(r){return r.json();}).then(function(result){if(!result.ok)throw new Error(result.message);return fetch(localizedUrl(root),{credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){return r.text();}).then(function(html){var page=new DOMParser().parseFromString(html,'text/html'),next=page.querySelector('.log-center');if(!next)throw new Error('Invalid response');root.replaceWith(next);bind(next);showToast(next,result.message,false);});}).catch(function(error){connectionToggle.checked=!wanted;connectionToggle.disabled=false;showToast(root,error.message,true);});});
  var edit=form.querySelector('[data-log-center-edit]');if(edit)edit.addEventListener('click',function(){var fields=form.querySelector('[data-log-center-connection-fields]'),save=form.querySelector('[data-log-center-save]');fields.hidden=false;save.hidden=false;edit.hidden=true;var input=fields.querySelector('input');if(input)input.focus();});
 }
 var root=document.querySelector('.log-center');if(root)bind(root);
}());
(function(){
 'use strict'; var timer=null;
 function root(){return document.querySelector('[data-log-center-viewer]');}
 function bind(){var box=root();if(!box||box.dataset.bound)return;box.dataset.bound='1';var log=box.querySelector('[data-log-center-log]'),severity=box.querySelector('[data-log-center-severity]'),search=box.querySelector('[data-log-center-search]'),colors=box.querySelector('[data-log-center-colors]'),live=box.querySelector('[data-log-center-live]'),status=box.querySelector('[data-log-center-live-status]');
  function filter(){var level=severity?severity.value:'',needle=search?search.value.trim().toLowerCase():'',shown=0;log.querySelectorAll('[data-log-center-status]').forEach(function(row){row.hidden=!!((level&&row.dataset.logCenterStatus!==level)||(needle&&row.textContent.toLowerCase().indexOf(needle)<0));if(!row.hidden)shown++;});}
  function colour(){var on=!colors||colors.checked;log.classList.toggle('is-colored',on);try{localStorage.setItem('log_center_colors',on?'1':'0');}catch(e){}}
  function reload(){var url=new URL(location.href),app=document.querySelector('.log-center'),file=box.dataset.logCenterFileName||'';if(app&&app.dataset.language)url.searchParams.set('lang',app.dataset.language);if(file)url.searchParams.set('viewer_file',file);fetch(url.toString(),{credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){if(!r.ok)throw Error('HTTP '+r.status);return r.text();}).then(function(html){var page=new DOMParser().parseFromString(html,'text/html'),viewer=page.querySelector('[data-log-center-viewer]'),next=viewer&&viewer.querySelector('[data-log-center-log]');if(next&&(!file||viewer.dataset.logCenterFileName===file)){log.innerHTML=next.innerHTML;filter();colour();log.scrollTop=log.scrollHeight;}if(status)status.textContent=new Date().toLocaleTimeString();}).catch(function(e){if(status)status.textContent=e.message;});}
  function liveState(){if(timer){clearInterval(timer);timer=null}if(!live||box.dataset.logCenterType==='update'){if(live){live.checked=false;live.disabled=true}return;}live.disabled=false;if(live.checked)timer=setInterval(reload,5000);}
  if(severity)severity.addEventListener('change',filter);if(search)search.addEventListener('input',filter);if(colors){try{colors.checked=localStorage.getItem('log_center_colors')!=='0'}catch(e){}colors.addEventListener('change',colour)}if(live)live.addEventListener('change',liveState)
  function viewerUrl(){var url=new URL(location.href),app=document.querySelector('.log-center');if(app&&app.dataset.language)url.searchParams.set('lang',app.dataset.language);return url.toString();}
  box.querySelectorAll('[data-log-center-type],[data-log-center-file],[data-log-center-view-toggle]').forEach(function(input){input.addEventListener('change',function(){var form=input.closest('form');if(!form)return;var data=new FormData(form);if(input.matches('[data-log-center-type]')){data.set('log_center_action','viewer_type');data.set('viewer_type',input.value);}if(input.matches('[data-log-center-view-toggle]'))data.set('viewer_file',box.dataset.logCenterFileName||'');input.disabled=true;fetch(viewerUrl(),{method:'POST',body:data,credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest','Cache-Control':'no-cache'}}).then(function(response){if(!response.ok)throw new Error('HTTP '+response.status);return response.text();}).then(function(html){var next=new DOMParser().parseFromString(html,'text/html').querySelector('[data-log-center-viewer]');if(!next)throw new Error('Invalid response');box.replaceWith(next);bind();}).catch(function(error){input.disabled=false;if(status)status.textContent=error.message;});});});var archive=box.querySelector('[data-log-center-archive-form]');if(archive)archive.addEventListener('submit',function(e){if(!confirm(archive.dataset.confirm||''))e.preventDefault();else archive.querySelector('[name="confirmed"]').value='1';});colour();filter();log.scrollTop=log.scrollHeight;liveState();}
 document.addEventListener('click',function(event){var row=event.target.closest('[data-log-center-detail]');if(!row)return;var dialog=document.querySelector('.log-center-detail-dialog');if(!dialog)return;var data={};try{data=JSON.parse(row.dataset.logCenterDetail)}catch(e){}dialog.querySelector('[data-log-center-detail-line]').textContent=data.line||'';dialog.querySelector('[data-log-center-detail-trace]').textContent=data.trace||'';if(typeof dialog.showModal==='function'&&!dialog.open)dialog.showModal();});
 document.addEventListener('keydown',function(event){if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-log-center-detail]')){event.preventDefault();event.target.click();}});
 bind();
}());
(function(){'use strict';
 function runtimeName(form){var field=form&&form.querySelector('input[name="runtime_name"]');return field?field.value:'';}
 function runtimeUrl(root){var url=new URL(location.href);if(root&&root.dataset.language)url.searchParams.set('lang',root.dataset.language);return url.toString();}
 function syncRuntimeControls(root){root=root||document;var enabledForm=root.querySelector('[data-log-center-runtime-form] input[name="runtime_name"][value="enabled"]');var accessForm=root.querySelector('[data-log-center-runtime-form] input[name="runtime_name"][value="access"]');var traceForm=root.querySelector('[data-log-center-runtime-form] input[name="runtime_name"][value="trace"]');var runtimeOn=!!(enabledForm&&enabledForm.closest('form').querySelector('[data-log-center-runtime]').checked);var traceOn=!!(traceForm&&traceForm.closest('form').querySelector('[data-log-center-runtime]').checked);var accessOn=!!(accessForm&&accessForm.closest('form').querySelector('[data-log-center-runtime]').checked);var displayGroup=root.querySelector('[data-log-center-runtime-display-group]');if(displayGroup)displayGroup.hidden=!runtimeOn||!traceOn;root.querySelectorAll('[data-log-center-runtime-form]').forEach(function(form){var name=runtimeName(form),toggle=form.querySelector('[data-log-center-runtime]');if(!toggle)return;var disabled=name!=='enabled'&&name!=='trace'&&!runtimeOn;if(name==='admin_display'||name==='frontend_display')disabled=disabled||!traceOn;if(['access_slow','access_errors','access_ajax_api_errors','access_background','access_sampling'].indexOf(name)!==-1)disabled=disabled||!accessOn;toggle.disabled=disabled;form.classList.toggle('is-disabled',disabled);form.setAttribute('aria-disabled',disabled?'true':'false');});}
 function showRuntimeToast(root,message,error){var toast=root.querySelector('.log-center-toast');if(!toast||!message)return;toast.hidden=false;toast.textContent=message;toast.classList.toggle('error',!!error);toast.classList.toggle('wbce-admin-toast--error',!!error);toast.classList.add('is-visible');window.setTimeout(function(){toast.classList.remove('is-visible');window.setTimeout(function(){toast.hidden=true;},180);},3500);}
 document.addEventListener('change',function(event){var toggle=event.target;if(!toggle.matches('[data-log-center-runtime]'))return;var form=toggle.closest('[data-log-center-runtime-form]'),current=document.querySelector('.log-center');if(!form||!current)return;var wanted=toggle.checked,data=new FormData(form);/* Do not rely on a checkbox surviving a synchronous disabled-state update. */data.set('enabled',wanted?'1':'0');syncRuntimeControls(current);toggle.disabled=true;fetch(runtimeUrl(current),{method:'POST',body:data,credentials:'same-origin',cache:'no-store',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json','Cache-Control':'no-cache'}}).then(function(response){if(!response.ok)throw new Error('HTTP '+response.status);return response.json();}).then(function(result){if(!result.ok||!result.config)throw new Error(result.message||'Saving failed');current.querySelectorAll('[data-log-center-runtime-form]').forEach(function(item){var name=runtimeName(item),input=item.querySelector('[data-log-center-runtime]');if(input&&Object.prototype.hasOwnProperty.call(result.config,name))input.checked=!!result.config[name];});syncRuntimeControls(current);showRuntimeToast(current,result.message||'',false);}).catch(function(error){toggle.checked=!wanted;toggle.disabled=false;syncRuntimeControls(current);showRuntimeToast(current,error.message,true);});});
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){syncRuntimeControls(document.querySelector('.log-center'));});else syncRuntimeControls(document.querySelector('.log-center'));
}());
