<?php
defined('WB_PATH') && isset($admin) or die('Access denied');
require_once __DIR__.'/CookieBanner.php';
$COOKIE_BANNER=array(); require __DIR__.'/languages/EN.php';
$language=__DIR__.'/languages/'.strtoupper(defined('LANGUAGE')?(string)LANGUAGE:'EN').'.php'; if(is_file($language)) require $language;
$t=static fn($key)=>$COOKIE_BANNER[$key]??$key;
$h=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$cookieBannerFtan=explode('=', $admin->getFTAN(false), 2);$cookieBannerFtanName=$cookieBannerFtan[0]??'formtoken';$cookieBannerFtanValue=$cookieBannerFtan[1]??'';
$settings=WbceCookieBanner::settings();$providers=WbceCookieBanner::providers();$categories=WbceCookieBanner::categories();$configuredCategories=array_filter($categories,static fn($category)=>!empty($category['scripts'])||!empty($category['direct_integration']));$directByCategory=array();foreach(WbceCookieBanner::directIntegrations($settings) as $id=>$integration)if(!empty($integration['ready']))$directByCategory[$integration['category']][]=$integration['name'];

?>
<link rel="stylesheet" href="<?php echo $h(WB_URL.'/modules/cookie_banner/assets/admin.css?v=1.0.30'); ?>">
<main class="cookie-banner-tool">
 <header class="cookie-banner-hero"><i class="fa fa-shield" aria-hidden="true"></i><div><h2><?php echo $h($t('title')); ?></h2><p><?php echo $h($t('intro')); ?></p></div></header>
 <?php if (!$providers): ?>
 <section class="cookie-banner-card"><h3><?php echo $h($t('no_provider_title')); ?></h3><p><?php echo $h($t('no_provider_text')); ?></p></section>
 <?php else: ?>
 <form method="post" class="cookie-banner-form" data-api="<?php echo $h(WB_URL.'/modules/cookie_banner/api.php'); ?>">
  <input type="hidden" name="<?php echo $h($cookieBannerFtanName); ?>" value="<?php echo $h($cookieBannerFtanValue); ?>" data-cookie-ftan="<?php echo $h($cookieBannerFtanValue); ?>">
  <section class="cookie-banner-card cookie-provider-selection"><label class="cookie-banner-switch"><input type="checkbox" name="enabled" value="1"<?php echo ($settings['enabled']??'0')==='1'?' checked':''; ?>><span></span><?php echo $h($t('enable')); ?></label><h3><?php echo $h($t('provider')); ?></h3><div class="cookie-provider-picker"><div class="cookie-provider-cards"><?php foreach($providers as $id=>$provider): ?><label class="cookie-provider-card"><input type="radio" name="provider" value="<?php echo $h($id); ?>"<?php echo ($settings['provider']??'')===$id?' checked':''; ?>><span><b><?php echo $h($provider['name']??$id); ?></b><small><?php echo $h($provider['description']??''); ?></small></span></label><?php endforeach; ?></div></div></section>
  <section class="cookie-banner-card cookie-category-block"<?php echo $configuredCategories?'':' hidden'; ?>><h3><?php echo $h($t('categories')); ?></h3><p>Die Kategorien enthalten automatisch die unter „Externe Skripte“ zugeordneten Einbindungen.</p><div class="cookie-banner-categories" data-category-list><?php foreach($configuredCategories as $id=>$category): ?><article><strong><?php echo $h($category['name']); ?></strong><small><?php echo $h($category['description']); ?></small><ul class="cookie-category-services"><?php foreach((array)$category['scripts'] as $script): ?><li><a href="<?php echo $h($script); ?>" target="_blank" rel="noopener noreferrer"><?php echo $h($script); ?></a></li><?php endforeach; ?><?php foreach($directByCategory[$id]??array() as $integration): ?><li><?php echo $h($integration); ?></li><?php endforeach; ?></ul></article><?php endforeach; ?></div></section>
  <section class="cookie-banner-card cookie-general-settings">
  <div class="cookie-banner-grid">
   <label><?php echo $h($t('privacy_url')); ?><input name="privacy_url" value="<?php echo $h($settings['privacy_url']??''); ?>"></label>
   <label><?php echo $h($t('title')); ?><input name="title" value="<?php echo $h($settings['title']??''); ?>"></label>
   <label class="full"><?php echo $h($t('notice')); ?><textarea name="text" rows="3"><?php echo $h($settings['text']??''); ?></textarea></label>
   <label><?php echo $h($t('accept')); ?><input name="accept" value="<?php echo $h($settings['accept']??''); ?>"></label><label><?php echo $h($t('reject')); ?><input name="reject" value="<?php echo $h($settings['reject']??''); ?>"></label><label><?php echo $h($t('selection')); ?><input name="save" value="<?php echo $h($settings['save']??''); ?>"></label>
  </div>
  </section>
  <section class="cookie-banner-card cookie-tracking-block"><h3>Direkte Einbindungen</h3><p>Jede Gruppe entspricht einer eigenen Cookie-Kategorie. Dienste laden erst nach Zustimmung.</p>
   <section class="cookie-direct-group"><header><strong>Analyse</strong><small>Reichweitenmessung, Statistik und Tag-Verwaltung.</small></header><div class="cookie-banner-grid">
    <div><label class="cookie-banner-switch"><input type="checkbox" name="google_analytics_enabled" value="1"<?php echo ($settings['google_analytics_enabled']??'0')==='1'?' checked':''; ?>><span></span>Google Analytics aktivieren</label><div data-integration-options="google_analytics"><label>Google Analytics Mess-ID<input name="google_analytics_id" placeholder="G-XXXXXXXXXX" value="<?php echo $h($settings['google_analytics_id']??''); ?>"></label></div></div><div><label class="cookie-banner-switch"><input type="checkbox" name="google_tag_manager_enabled" value="1"<?php echo ($settings['google_tag_manager_enabled']??'0')==='1'?' checked':''; ?>><span></span>Google Tag Manager aktivieren</label><div data-integration-options="google_tag_manager"><label>Container-ID<input name="google_tag_manager_id" placeholder="GTM-XXXXXXX" value="<?php echo $h($settings['google_tag_manager_id']??''); ?>"></label></div></div><div><label class="cookie-banner-switch"><input type="checkbox" name="matomo_enabled" value="1"<?php echo ($settings['matomo_enabled']??'0')==='1'?' checked':''; ?>><span></span>Matomo aktivieren</label><div data-integration-options="matomo"><label>Matomo-URL<input type="url" name="matomo_url" placeholder="https://analytics.example.org/" value="<?php echo $h($settings['matomo_url']??''); ?>"></label><label>Matomo Site-ID<input type="number" min="1" name="matomo_site_id" value="<?php echo $h($settings['matomo_site_id']??''); ?>"></label></div></div></div></section>
   <section class="cookie-direct-group"><header><strong>Marketing</strong><small>Kampagnen-, Zielgruppen- und Conversion-Messung.</small></header><div class="cookie-banner-grid"><div><label class="cookie-banner-switch"><input type="checkbox" name="google_ads_enabled" value="1"<?php echo ($settings['google_ads_enabled']??'0')==='1'?' checked':''; ?>><span></span>Google Ads Conversion Tracking</label><div data-integration-options="google_ads"><label>Google Ads-ID<input name="google_ads_id" placeholder="AW-123456789" value="<?php echo $h($settings['google_ads_id']??''); ?>"></label></div></div><div><label class="cookie-banner-switch"><input type="checkbox" name="meta_pixel_enabled" value="1"<?php echo ($settings['meta_pixel_enabled']??'0')==='1'?' checked':''; ?>><span></span>Meta Pixel aktivieren</label><div data-integration-options="meta_pixel"><label>Meta Pixel-ID<input name="meta_pixel_id" inputmode="numeric" value="<?php echo $h($settings['meta_pixel_id']??''); ?>"></label></div></div></div></section>
   <section class="cookie-direct-group"><header><strong>Medien</strong><small>Eingebettete Videos werden bis zur Zustimmung blockiert.</small></header><div class="cookie-banner-grid"><label class="cookie-banner-switch"><input type="checkbox" name="youtube_enabled" value="1"<?php echo ($settings['youtube_enabled']??'0')==='1'?' checked':''; ?>><span></span>YouTube einbinden</label><label class="cookie-banner-switch"><input type="checkbox" name="vimeo_enabled" value="1"<?php echo ($settings['vimeo_enabled']??'0')==='1'?' checked':''; ?>><span></span>Vimeo einbinden</label></div></section>
   <section class="cookie-direct-group"><header><strong>Karten</strong><small>Eingebettete Karten werden bis zur Zustimmung blockiert.</small></header><div class="cookie-banner-grid"><label class="cookie-banner-switch"><input type="checkbox" name="google_maps_enabled" value="1"<?php echo ($settings['google_maps_enabled']??'0')==='1'?' checked':''; ?>><span></span>Google Maps einbinden</label><label class="cookie-banner-switch"><input type="checkbox" name="openstreetmap_enabled" value="1"<?php echo ($settings['openstreetmap_enabled']??'0')==='1'?' checked':''; ?>><span></span>OpenStreetMap einbinden</label></div></section>
  </section>
  <section class="cookie-banner-card cookie-external-scripts"><h3>Externe Skripte</h3><p>Eine Zeile je Skript: Kategorie <code>|</code> URL. Sie werden erst nach Zustimmung zur jeweiligen Kategorie geladen.</p><textarea name="external_scripts" rows="5" placeholder="analytics|https://example.org/analytics.js
marketing|https://example.org/pixel.js"><?php echo $h($settings['external_scripts']??''); ?></textarea></section>
  <?php foreach(WbceCookieBanner::settingsSections() as $section) if(is_string($section)) echo $section; ?>
  <section class="cookie-banner-card cookie-save-block"><button class="button" name="cookie_banner_save" value="1"><?php echo $h($t('save')); ?></button></section>
 </form>
 <?php endif; ?>
 <div class="cookie-banner-toast" role="status" aria-live="polite"></div>
</main>
<script src="<?php echo $h(WB_URL.'/modules/cookie_banner/assets/admin.js?v=1.0.34'); ?>"></script>
