<?php
defined('WB_PATH') or die('No direct access');if(!is_file(WB_PATH.'/modules/two_factor/Language.php')||!is_file(WB_PATH.'/modules/two_factor/Registry.php'))return;require_once WB_PATH.'/modules/two_factor/Language.php';if(is_file(WB_PATH.'/modules/two_factor/Compatibility.php'))require_once WB_PATH.'/modules/two_factor/Compatibility.php';
if(is_file(WB_PATH.'/modules/two_factor/Registry.php')){require_once WB_PATH.'/modules/two_factor/Registry.php';require_once __DIR__.'/Service.php';WbceTwoFactorRegistry::register('whatsapp',array(
 'name'=>wbce_two_factor_t('provider_name',array(),'two_factor_whatsapp'),'description'=>wbce_two_factor_t('provider_description',array(),'two_factor_whatsapp'),'icon'=>'fa-whatsapp','usage'=>static function()use($database){return(new WbceWhatsAppFactorService($database))->usage();},'profile_url'=>WB_URL.'/modules/two_factor_whatsapp/profile.php','configured'=>static function($userId)use($database){return(new WbceWhatsAppFactorService($database))->isEnabled($userId);},'system_configured'=>static function()use($database){return(new WbceWhatsAppFactorService($database))->isConfigured();},
 'disable_challenge'=>static function($userId)use($database){(new WbceWhatsAppFactorService($database))->sendCode($userId,true);return array('type'=>'code','message'=>wbce_two_factor_t('code_sent'));},
 'verify_disable'=>static function($userId,$value)use($database){return(new WbceWhatsAppFactorService($database))->verify($userId,$value);},
 'admin_config'=>static function()use($database){$s=new WbceWhatsAppFactorService($database);$h=static function($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');};return '<form><h3>'.$h(wbce_two_factor_t('provider_name',array(),'two_factor_whatsapp')).'</h3><label>'.$h(wbce_two_factor_t('phone_number_id',array(),'two_factor_whatsapp')).'<input class="form-control" name="phone_number_id" value="'.$h($s->setting('phone_number_id')).'" inputmode="numeric" required></label><label>'.$h(wbce_two_factor_t('api_version',array(),'two_factor_whatsapp')).'<input class="form-control" name="api_version" value="'.$h($s->setting('api_version','23.0')).'" required></label><label>'.$h(wbce_two_factor_t('template_name',array(),'two_factor_whatsapp')).'<input class="form-control" name="template_name" value="'.$h($s->setting('template_name')).'" required></label><label>'.$h(wbce_two_factor_t('template_language',array(),'two_factor_whatsapp')).'<input class="form-control" name="template_language" value="'.$h($s->setting('template_language','de')).'" required></label><label class="wide">'.$h(wbce_two_factor_t('access_token',array(),'two_factor_whatsapp')).'<input class="form-control" type="password" name="access_token" autocomplete="new-password" placeholder="'.$h(wbce_two_factor_t($s->setting('access_token')!==''?'token_saved':'token_enter',array(),'two_factor_whatsapp')).'"></label><button type="submit" class="button wbce-admin-button">'.$h(wbce_two_factor_t('save',array(),'two_factor_whatsapp')).'</button></form>';},
 'save_config'=>static function($input)use($database){$s=new WbceWhatsAppFactorService($database);$values=array('phone_number_id'=>trim((string)($input['phone_number_id']??'')),'api_version'=>trim((string)($input['api_version']??'')),'template_name'=>trim((string)($input['template_name']??'')),'template_language'=>trim((string)($input['template_language']??'')));if(!preg_match('/^[0-9]+$/',$values['phone_number_id'])||!preg_match('/^[0-9]+(?:\.[0-9]+)?$/',$values['api_version'])||!preg_match('/^[A-Za-z0-9_]+$/',$values['template_name'])||!preg_match('/^[A-Za-z]{2,3}(?:_[A-Za-z]{2})?$/',$values['template_language']))throw new RuntimeException(wbce_two_factor_t('config_invalid',array(),'two_factor_whatsapp'));foreach($values as$key=>$value)if(!$s->setSetting($key,$value))throw new RuntimeException(wbce_two_factor_t('save_failed',array(),'two_factor_whatsapp'));$token=trim((string)($input['access_token']??''));if($token!==''&&!$s->setSetting('access_token',$token))throw new RuntimeException(wbce_two_factor_t('save_failed',array(),'two_factor_whatsapp'));}
));}
if(!function_exists('wbce_add_filter')||!class_exists('WbceAuthFactorManager'))return;
wbce_add_filter('admin.assets',function($assets){$assets[]=array('type'=>'css','url'=>WB_URL.'/modules/two_factor_whatsapp/theme.css?v=1.1.15','id'=>'two-factor-whatsapp-theme');return $assets;},10);require_once __DIR__.'/Provider.php';WbceAuthFactorManager::register(new WbceWhatsAppFactorProvider($database));
if(class_exists('WbceTwoFactorCompatibility'))WbceTwoFactorCompatibility::enforce();
