<?php
/** Modern CAPTCHA and ASP settings UI for WBCE. */
if (!function_exists('captcha_control_text')) {
    function captcha_control_text($text)
    {
        $decoded = html_entity_decode((string)$text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        return htmlentities($decoded, ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5, 'UTF-8');
    }
}
?>
<style>
.captcha-app{--cc-primary:#2271b1;--cc-primary-dark:#135e96;--cc-border:#dcdcde;--cc-muted:#50575e;--cc-bg:#f6f7f7;color:#1d2327;max-width:1180px}
.captcha-hero{padding:1.45rem 1.6rem;border-radius:10px;background:linear-gradient(135deg,var(--cc-primary),var(--cc-primary-dark));color:#fff;margin:0 0 1rem;box-shadow:0 3px 10px rgba(19,94,150,.18)}
.captcha-hero h2{color:#fff;margin:0 0 .3rem;font-size:1.55rem}.captcha-hero p{margin:0;opacity:.92;max-width:760px;line-height:1.5}
.captcha-section{background:var(--cc-bg);border:1px solid #c3c4c7;border-radius:10px;padding:1.1rem;margin:1rem 0}.captcha-section-head{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1rem}.captcha-section-head h3{margin:0;font-size:1.2rem}.captcha-section-head p{margin:.3rem 0 0;color:var(--cc-muted)}
.captcha-step{display:inline-flex;align-items:center;justify-content:center;min-width:27px;height:27px;border-radius:50%;background:var(--cc-primary);color:#fff;font-weight:700;margin-right:.45rem}
.captcha-provider-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:1rem}.captcha-provider{position:relative;display:flex;flex-direction:column;min-height:118px;padding:1rem;background:#fff;border:2px solid var(--cc-border);border-radius:9px;box-shadow:0 1px 3px rgba(0,0,0,.06);cursor:pointer;transition:.15s;box-sizing:border-box}.captcha-provider:hover{border-color:#72aee6;box-shadow:0 4px 12px rgba(0,0,0,.1);transform:translateY(-1px)}.captcha-provider.is-selected{border-color:var(--cc-primary);box-shadow:0 0 0 1px var(--cc-primary),0 4px 12px rgba(34,113,177,.15)}
.captcha-provider input{position:absolute;opacity:0;pointer-events:none}.captcha-provider-title{display:flex;align-items:center;justify-content:space-between;gap:.5rem;margin-bottom:.45rem}.captcha-provider-title strong{font-size:1.05rem}.captcha-provider-state{display:none;border-radius:12px;padding:.2rem .55rem;font-size:.78rem;background:#2e7d32;color:#fff}.captcha-provider.is-selected .captcha-provider-state{display:inline-block}.captcha-provider small{color:var(--cc-muted);line-height:1.45}.captcha-provider-check{position:absolute;right:12px;bottom:10px;width:20px;height:20px;border-radius:50%;border:2px solid #a7aaad}.captcha-provider.is-selected .captcha-provider-check{border-color:var(--cc-primary);background:var(--cc-primary);box-shadow:inset 0 0 0 4px #fff}
.captcha-single-provider{display:flex;flex-direction:column;gap:.3rem;padding:1rem;background:#fff;border:1px solid var(--cc-border);border-radius:9px}.captcha-single-provider small{color:var(--cc-muted)}
.captcha-settings-card,.captcha-usage-card,.captcha-asp-card{background:#fff;border:1px solid var(--cc-border);border-radius:9px;padding:1rem;box-shadow:0 1px 3px rgba(0,0,0,.05)}.captcha-provider-settings fieldset{border:0;margin:0;padding:0}.captcha-provider-settings legend{font-size:1.08rem;font-weight:700;padding:0;margin:0 0 .8rem}.captcha-provider-settings p{margin:.75rem 0}.captcha-provider-settings input[type=text],.captcha-provider-settings input[type=password],.captcha-provider-settings input[type=number],.captcha-provider-settings input[type=url],.captcha-provider-settings select,.captcha-textarea,.captcha-login-select{max-width:100%;padding:.55rem .65rem;border:1px solid #8c8f94;border-radius:5px;background:#fff;box-sizing:border-box}.captcha-provider-settings input:focus,.captcha-provider-settings select:focus,.captcha-textarea:focus,.captcha-login-select:focus{border-color:var(--cc-primary);box-shadow:0 0 0 1px var(--cc-primary);outline:0}
.captcha-usage-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:1rem}.captcha-usage-card{display:flex;align-items:center;justify-content:space-between;gap:1rem;min-height:78px;box-sizing:border-box}.captcha-usage-copy strong{display:block;margin-bottom:.25rem}.captcha-usage-copy small{display:block;color:var(--cc-muted);line-height:1.35}.captcha-login-card{display:block}.captcha-login-card .captcha-login-select{width:100%;margin-top:.65rem}
.captcha-switch{position:relative;display:inline-block;flex:0 0 auto;width:46px;height:25px}.captcha-switch input{position:absolute;opacity:0;width:1px;height:1px}.captcha-slider{position:absolute;inset:0;background:#a7aaad;border-radius:25px;cursor:pointer;transition:.2s}.captcha-slider:before{content:'';position:absolute;width:19px;height:19px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s;box-shadow:0 1px 2px rgba(0,0,0,.25)}.captcha-switch input:checked+.captcha-slider{background:var(--cc-primary)}.captcha-switch input:checked+.captcha-slider:before{transform:translateX(21px)}.captcha-switch input:focus+.captcha-slider{box-shadow:0 0 0 2px #fff,0 0 0 4px var(--cc-primary)}
.captcha-asp-card{display:flex;align-items:center;justify-content:space-between;gap:1rem}.captcha-asp-icon{display:flex;align-items:center;justify-content:center;flex:0 0 46px;height:46px;border-radius:9px;background:#e9f3fb;color:var(--cc-primary);font-size:1.35rem}.captcha-asp-copy{flex:1}.captcha-asp-copy strong{display:block;font-size:1.05rem;margin-bottom:.25rem}.captcha-asp-copy small{color:var(--cc-muted);line-height:1.45}.captcha-text-config{margin-top:1rem}.captcha-text-config label{display:block;font-weight:700;margin-bottom:.55rem}.captcha-textarea{width:100%;min-height:260px;resize:vertical;font-family:monospace}
.captcha-actions{display:flex;flex-wrap:wrap;gap:.65rem;justify-content:flex-end;margin:1rem 0}.captcha-button{border:0;border-radius:5px;padding:.62rem 1rem;font-weight:600;cursor:pointer}.captcha-button-primary{background:var(--cc-primary);color:#fff}.captcha-button-primary:hover{background:var(--cc-primary-dark)}.captcha-button-secondary{background:#fff;color:#2c3338;border:1px solid #8c8f94}.captcha-button-secondary:hover{border-color:var(--cc-primary);color:var(--cc-primary)}
@media(max-width:640px){.captcha-hero{padding:1.15rem}.captcha-section{padding:.8rem}.captcha-provider-grid,.captcha-usage-grid{grid-template-columns:1fr}.captcha-asp-card{align-items:flex-start}.captcha-actions{justify-content:stretch}.captcha-button{flex:1}}
</style>
<div class="captcha-app" id="captcha-app">
<header class="captcha-hero"><h2><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['HEADING']); ?></h2><p><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['HOWTO']); ?></p></header>
<form name="captcha_settings" action="<?php echo htmlspecialchars($returnUrl,ENT_QUOTES,'UTF-8'); ?>" method="post">
<?php echo $admin->getFTAN(); ?>
<section class="captcha-section"><div class="captcha-section-head"><div><h3><span class="captcha-step">1</span><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['CAPTCHA_TYPE']); ?></h3><p>W&auml;hlen Sie den Schutz aus, der auf dieser Website verwendet werden soll.</p></div></div>
<?php if(count($captcha_providers)>1): ?><div class="captcha-provider-grid"><?php foreach($captcha_providers as $key=>$provider): ?><label class="captcha-provider<?php echo $key===$captcha_type?' is-selected':''; ?>"><input<?php echo $key===$captcha_type?' checked':''; ?> type="radio" name="captcha_type" value="<?php echo htmlspecialchars($key,ENT_QUOTES,'UTF-8'); ?>"><span class="captcha-provider-title"><strong><?php echo htmlspecialchars($provider['name'],ENT_QUOTES,'UTF-8'); ?></strong><span class="captcha-provider-state">Aktiv</span></span><?php if(!empty($provider['description'])): ?><small><?php echo htmlspecialchars($provider['description'],ENT_QUOTES,'UTF-8'); ?></small><?php else: ?><small>Installierter CAPTCHA-Anbieter</small><?php endif; ?><span class="captcha-provider-check" aria-hidden="true"></span></label><?php endforeach; ?></div><?php elseif(count($captcha_providers)===1): $key=(string)key($captcha_providers);$provider=current($captcha_providers); ?><input type="hidden" name="captcha_type" value="<?php echo htmlspecialchars($key,ENT_QUOTES,'UTF-8'); ?>"><div class="captcha-single-provider"><strong>Aktiver Provider: <?php echo htmlspecialchars($provider['name'],ENT_QUOTES,'UTF-8'); ?></strong><small><?php echo htmlspecialchars(!empty($provider['description'])?$provider['description']:'Installierter CAPTCHA-Anbieter',ENT_QUOTES,'UTF-8'); ?></small></div><?php else: ?><blockquote><strong>Kein CAPTCHA-Provider installiert.</strong></blockquote><?php endif; ?></section>
<section class="captcha-section"><div class="captcha-section-head"><div><h3><span class="captcha-step">2</span>Konfiguration</h3><p>Die Einstellungen des ausgew&auml;hlten CAPTCHA-Anbieters.</p></div></div><div class="captcha-settings-card">
<?php foreach($captcha_settings_sections as $settingsProviderId=>$providerSettings): ?><div class="captcha-provider-settings" data-provider="<?php echo htmlspecialchars($settingsProviderId,ENT_QUOTES,'UTF-8'); ?>"<?php echo $settingsProviderId===$captcha_type?'':' hidden'; ?>><?php echo implode('',$providerSettings); ?></div><?php endforeach; ?>
<div class="captcha-provider-settings captcha-text-config" id="text_qa" data-provider="text"<?php echo $captcha_type==='text'?'':' hidden'; ?>><label for="captcha-text-qa"><?php echo htmlspecialchars($MOD_CAPTCHA_CONTROL['CAPTCHA_ENTER_TEXT'],ENT_QUOTES,'UTF-8'); ?></label><textarea class="captcha-textarea" id="captcha-text-qa" name="text_qa" rows="14"><?php echo htmlspecialchars($text_qa,ENT_QUOTES,'UTF-8'); ?></textarea></div>
<div class="captcha-provider-empty"<?php echo isset($captcha_settings_sections[$captcha_type])||$captcha_type==='text'?' hidden':''; ?>>F&uuml;r diesen Anbieter sind keine weiteren Einstellungen erforderlich.</div></div></section>
<section class="captcha-section"><div class="captcha-section-head"><div><h3><span class="captcha-step">3</span>Einsatzbereiche</h3><p>Legen Sie fest, an welchen Stellen der CAPTCHA-Schutz verwendet wird.</p></div></div><div class="captcha-usage-grid">
<div class="captcha-usage-card captcha-login-card"><div class="captcha-usage-copy"><strong>Admin-Login</strong><small>Sch&uuml;tzt die Anmeldung im Administrationsbereich.</small></div><select class="captcha-login-select" name="captcha_login_mode"><option value="off"<?php echo $captcha_login_mode==='off'?' selected':''; ?>>Aus</option><option value="after_failures"<?php echo $captcha_login_mode==='after_failures'?' selected':''; ?>>Nach mehreren Fehlversuchen</option><option value="always"<?php echo $captcha_login_mode==='always'?' selected':''; ?>>Immer</option></select></div>
<div class="captcha-usage-card"><div class="captcha-usage-copy"><strong>Passwort zur&uuml;cksetzen</strong><small>Sch&uuml;tzt das Anfordern eines neuen Passworts.</small></div><label class="captcha-switch"><input type="checkbox" name="captcha_password_reset" value="1"<?php echo $captcha_password_reset?' checked':''; ?>><span class="captcha-slider"></span></label></div>
<div class="captcha-usage-card"><div class="captcha-usage-copy"><strong>Registrierung</strong><small><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['CAPTCHA_EXP']); ?></small></div><label class="captcha-switch"><input type="checkbox" name="enabled_captcha" value="1"<?php echo (string)$enabled_captcha==='1'||$enabled_captcha===true?' checked':''; ?>><span class="captcha-slider"></span></label></div>
</div></section>
<section class="captcha-section"><div class="captcha-section-head"><div><h3>Advanced Spam Protection</h3><p>Zus&auml;tzlicher, f&uuml;r Besucher unsichtbarer Schutz gegen automatisierte Formulareingaben.</p></div></div><div class="captcha-asp-card"><span class="captcha-asp-icon" aria-hidden="true">&#128737;</span><div class="captcha-asp-copy"><strong><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['ASP_CONF']); ?></strong><small><?php echo captcha_control_text($MOD_CAPTCHA_CONTROL['ASP_EXP']); ?></small></div><label class="captcha-switch"><input type="checkbox" name="enabled_asp" value="1"<?php echo (string)$enabled_asp==='1'||$enabled_asp===true?' checked':''; ?>><span class="captcha-slider"></span></label></div></section>
<div class="captcha-actions"><button type="submit" class="captcha-button captcha-button-secondary" name="admin_tools" value="1"><?php echo captcha_control_text($HEADING['ADMINISTRATION_TOOLS']); ?></button><button type="submit" class="captcha-button captcha-button-primary" name="save_settings" value="1"><?php echo captcha_control_text($TEXT['SAVE']); ?></button></div>
</form></div>
<script>
(function(){var app=document.getElementById('captcha-app');if(!app)return;var choices=app.querySelectorAll('input[name="captcha_type"]');function updateProvider(){var selected=app.querySelector('input[name="captcha_type"]:checked')||app.querySelector('input[name="captcha_type"]'),selectedId=selected?selected.value:'',hasSettings=false;app.querySelectorAll('.captcha-provider').forEach(function(card){card.classList.toggle('is-selected',card.contains(selected));});app.querySelectorAll('.captcha-provider-settings').forEach(function(panel){var visible=panel.getAttribute('data-provider')===selectedId;panel.hidden=!visible;if(visible)hasSettings=true;});var empty=app.querySelector('.captcha-provider-empty');if(empty)empty.hidden=hasSettings;}choices.forEach(function(choice){choice.addEventListener('change',updateProvider);});updateProvider();}());
</script>
