<?php
/** Generic output adapters only; all business logic belongs to the registering module. */
final class WbceHookBridge
{
 private static $frontend=false,$users=false,$preferences=false,$newUserBaseline=0;
 private static function row($result){if(!is_object($result))return null;if(is_callable(array($result,'fetchRow')))return $result->fetchRow(MYSQLI_ASSOC);if(is_callable(array($result,'fetch_assoc')))return $result->fetch_assoc();return null;}
 private static function postedUsername(){
  $field=isset($_POST['username_fieldname'])?(string)$_POST['username_fieldname']:'';
  $username=$field!==''&&array_key_exists($field,$_POST)?(string)$_POST[$field]:(string)($_POST['username']??'');
  if(function_exists('wbce_normalize_username'))return wbce_normalize_username($username);
  $username=trim($username);return function_exists('mb_strtolower')?mb_strtolower($username,'UTF-8'):strtolower($username);
 }
 public static function emulatesHooks(){return defined('WBCE_HOOK_BRIDGE_EMULATES_HOOKS')&&WBCE_HOOK_BRIDGE_EMULATES_HOOKS;}
 public static function enableFrontendOutputHooks(){if(!self::emulatesHooks()||self::$frontend||PHP_SAPI==='cli')return;$path=(string)parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH);$admin=defined('ADMIN_URL')?rtrim((string)parse_url(ADMIN_URL,PHP_URL_PATH),'/'):'/admin';if($admin!==''&&($path===$admin||strpos($path,$admin.'/')===0))return;self::$frontend=true;ob_start(static function($html){if(stripos($html,'<html')===false||stripos($html,'</body>')===false)return $html;$id=(int)($GLOBALS['page_id']??0);$page=isset($GLOBALS['wb']->page)?$GLOBALS['wb']->page:array();return(string)wbce_apply_filters('frontend.page.output',$html,$id,$page);});}
 public static function enableUserFormHooks(){if(!self::emulatesHooks()||self::$users||PHP_SAPI==='cli')return;$path=(string)parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH);if(strpos($path,'/admin/users/')===false)return;self::$users=true;if(($_SERVER['REQUEST_METHOD']??'')==='POST'&&empty($_REQUEST['user_id'])){global $database;if(is_object($database)&&is_callable(array($database,'query'))){$result=$database->query('SELECT MAX(`user_id`) AS `last_id` FROM `{TP}users`');$row=self::row($result);self::$newUserBaseline=$row?(int)$row['last_id']:0;}}ob_start(static function($html){$id=isset($_REQUEST['user_id'])?(int)$_REQUEST['user_id']:0;$new=$id===0;if(($_SERVER['REQUEST_METHOD']??'')==='POST'){$id=self::dispatchUserMutation($id);}$extra=wbce_apply_filters('admin.user.form.sections','',$id,$new,array('bridge'=>true));$pos=strripos($html,'</form>');return $extra===''?$html:($pos===false?$html.$extra:substr($html,0,$pos).$extra.substr($html,$pos));});}
 public static function enablePreferencesHooks(){if(!self::emulatesHooks()||self::$preferences||PHP_SAPI==='cli')return;$path=(string)parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH);if(strpos($path,'/admin/preferences/')===false)return;self::$preferences=true;ob_start(static function($html){$id=(int)($_SESSION['USER_ID']??0);$sections=wbce_apply_filters('user.preferences.sections',array(),$id);if(!$sections)return $html;$extra=implode('',array_map('strval',$sections));$pos=strripos($html,'</main>');if($pos===false)$pos=strripos($html,'</body>');return $pos===false?$html.$extra:substr($html,0,$pos).$extra.substr($html,$pos);});}
 public static function dispatchUserMutation($id){global $database;if(!is_object($database)||!is_callable(array($database,'query'))||!is_callable(array($database,'escapeString')))return 0;$id=(int)$id;$new=$id===0;if($new){$username=self::postedUsername();if($username!==''){$r=$database->query("SELECT `user_id` FROM `{TP}users` WHERE `user_id`>".(int)self::$newUserBaseline." AND `username`='".$database->escapeString($username)."' ORDER BY `user_id` DESC LIMIT 1");$row=self::row($r);$id=$row?(int)$row['user_id']:0;}}if($id<1)return 0;if($new)wbce_do_action('user.created',$id,array(),$_POST);else wbce_do_action('user.updated',$id,array(),$_POST);if(!$new&&!empty($_POST['change_pswd']))wbce_do_action('user.password.changed',$id,'admin');return $id;}
}
