<?php
require_once __DIR__.'/vendor/TrustCaptcha.php';
final class WbceTrustCaptchaProvider
{
    public static function render(array $context){$site=trim((string)Settings::Get('captcha_trustcaptcha_sitekey',''));$key=trim((string)Settings::Get('captcha_trustcaptcha_apikey',''));if(!self::uuid($site)||$key===''){ $text=WbceCaptchaProviderUi::language(__DIR__,array('not_configured'=>'TrustCaptcha is not fully configured yet.'));return '<p class="warning">'.self::e($text['not_configured']).'</p>';}$theme=(string)Settings::Get('captcha_trustcaptcha_theme','light')==='dark'?'dark':'light';$minimal=(string)Settings::Get('captcha_trustcaptcha_minimal','1')==='1'?'true':'false';$asset='';if(!defined('WBCE_TRUSTCAPTCHA_ASSET_LOADED')){define('WBCE_TRUSTCAPTCHA_ASSET_LOADED',true);$asset='<script type="module" src="https://cdn.trustcomponent.com/trustcaptcha/3.0.1/trustcaptcha.esm.min.js"></script>';}return '<trustcaptcha-component sitekey="'.self::e($site).'" theme="'.$theme.'" token-field-name="tc-verification-token" minimal-data-mode="'.$minimal.'" full-width="true"></trustcaptcha-component>'.$asset;}
    public static function verify($input,array $context){$request=isset($context['request'])&&is_array($context['request'])?$context['request']:array();$rawToken=$request['tc-verification-token']??'';if(!is_scalar($rawToken))return false;$token=trim((string)$rawToken);$key=trim((string)Settings::Get('captcha_trustcaptcha_apikey',''));if(!self::validToken($token)||$key===''||!function_exists('curl_init'))return false;try{$captcha=new \TrustComponent\TrustCaptcha\TrustCaptcha($key);$result=$captcha->getVerificationResult($token);if($result->verificationPassed!==true||(float)$result->score>(float)Settings::Get('captcha_trustcaptcha_max_score','0.5'))return false;$originHost=strtolower(rtrim((string)parse_url((string)$result->origin,PHP_URL_HOST),'.'));$expectedHost=strtolower(rtrim((string)parse_url(defined('WB_URL')?WB_URL:'',PHP_URL_HOST),'.'));return $originHost!==''&&$expectedHost!==''&&hash_equals($expectedHost,$originHost);}catch(\Throwable $exception){return false;}}
    private static function validToken($token){if(!is_string($token)||$token===''||strlen($token)>16384)return false;$decoded=base64_decode($token,true);if(!is_string($decoded)||strlen($decoded)>8192)return false;$data=json_decode($decoded,true);return is_array($data)&&self::uuid((string)($data['verificationId']??''))&&(!isset($data['clientFailover'])||is_bool($data['clientFailover']));}
    private static function uuid($value){return is_string($value)&&preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/Di',$value)===1;}
    private static function e($value){return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
}
