<?php
final class WbceSecurityCenterDiagnostics
{
    public static function system()
    {
        $root=defined('WB_PATH')?WB_PATH:__DIR__;$total=@disk_total_space($root);$free=@disk_free_space($root);
        return array('PHP'=>PHP_VERSION,'SAPI'=>PHP_SAPI,'Betriebssystem'=>PHP_OS_FAMILY,'Serversoftware'=>(string)($_SERVER['SERVER_SOFTWARE']??'Unbekannt'),'HTTPS'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'Aktiv':'Nicht erkannt','php.ini'=>(string)(php_ini_loaded_file()?:'Nicht ermittelbar'),'Fehlerprotokoll'=>(string)(ini_get('error_log')?:'Nicht ermittelbar'),'Zeitzone'=>(string)date_default_timezone_get(),'Speicher gesamt'=>$total!==false?self::bytes($total):'Nicht ermittelbar','Speicher frei'=>$free!==false?self::bytes($free):'Nicht ermittelbar','PHP-Erweiterungen'=>(string)count(get_loaded_extensions()));
    }
    public static function phpInfoAvailable(){return function_exists('phpinfo')&&!in_array('phpinfo',array_map('trim',explode(',',(string)ini_get('disable_functions'))),true);}
    public static function phpInfoHtml(){if(!self::phpInfoAvailable())return '';ob_start();try{phpinfo(INFO_GENERAL|INFO_CONFIGURATION|INFO_MODULES);$html=(string)ob_get_clean();return $html;}catch(Throwable $exception){ob_end_clean();return '';}}
    public static function configuration($savedSettings=null)
    {
        $tests=array('display_errors'=>array('0','Fehler nicht öffentlich ausgeben'),'display_startup_errors'=>array('0','Startfehler nicht öffentlich ausgeben'),'log_errors'=>array('1','Fehler protokollieren'),'expose_php'=>array('0','PHP-Version nicht offenlegen'),'allow_url_include'=>array('0','Remote-Includes verhindern'),'session.cookie_httponly'=>array('1','Session-Cookie vor JavaScript schützen'),'session.use_strict_mode'=>array('1','Unbekannte Session-IDs ablehnen'),'session.use_only_cookies'=>array('1','Session-ID nur im Cookie'),'session.use_trans_sid'=>array('0','Session-ID nicht in URLs'),'phar.require_hash'=>array('1','PHAR-Signaturen verlangen'),'phar.readonly'=>array('1','PHAR-Erzeugung im Betrieb sperren'));
        $all=ini_get_all(null,true);require_once __DIR__.'/RuntimeConfig.php';$runtime=is_array($savedSettings)?$savedSettings:WbceSecurityCenterRuntimeConfig::load();$managed=(array)($runtime['php_runtime_settings']??array());$sessionActive=function_exists('session_status')&&session_status()===PHP_SESSION_ACTIVE;$rows=array();foreach($tests as $name=>$test){$actual=(string)ini_get($name);$ok=self::iniMatches($actual,$test[0]);$access=(int)($all[$name]['access']??0);$configured=array_key_exists($name,$managed)?(string)$managed[$name]:null;$enabled=self::iniEnabled($configured!==null?$configured:$actual);$runtimeChangeable=(bool)($access&1)&&!($sessionActive&&str_starts_with($name,'session.'))&&!str_starts_with($name,'phar.');$pending=$configured!==null&&!self::iniMatches($actual,$configured);$rows[]=array('name'=>$name,'actual'=>self::iniDisplay($actual),'expected'=>$test[0],'ok'=>$ok,'enabled'=>$enabled,'configured'=>$configured,'pending'=>$pending,'can_manage'=>$runtimeChangeable,'runtime_changeable'=>$runtimeChangeable,'recommendation'=>$test[1]);}return $rows;
    }
    public static function functions()
    {
        $groups=array('Befehlsausführung'=>array('exec','passthru','system','shell_exec','popen','proc_open','pcntl_exec'),'PHP-Ausführung'=>array('assert','eval','create_function'),'Informationen'=>array('phpinfo','posix_getlogin','get_current_user','getenv'),'Dateisystem'=>array('chmod','chown','symlink','link','putenv'));
        $disabled=array_map('trim',explode(',',(string)ini_get('disable_functions')));$rows=array();foreach($groups as $group=>$functions)foreach($functions as $function)$rows[]=array('group'=>$group,'function'=>$function,'available'=>function_exists($function)&&!in_array($function,$disabled,true));return $rows;
    }
    public static function errorLog($limit=100)
    {
        $path=(string)ini_get('error_log');if($path===''||!is_file($path)||!is_readable($path))return array();$size=(int)filesize($path);$handle=@fopen($path,'rb');if(!$handle)return array();$read=min($size,262144);if($read>0)fseek($handle,-$read,SEEK_END);$data=(string)fread($handle,$read);fclose($handle);$lines=array_values(array_filter(array_map(array(__CLASS__,'localizeLogLine'),preg_split('/\R/',trim($data)))));return array_slice($lines,-max(1,min(500,(int)$limit)));
    }
    public static function errorLogState(){$configured=(string)ini_get('error_log');$real=$configured!==''?realpath($configured):false;$file=$real!==false&&is_file($real)&&!is_link($configured);return array('configured'=>$configured,'path'=>$file?$real:$configured,'readable'=>$file&&is_readable($real),'writable'=>$file&&is_writable($real),'empty'=>$file&&filesize($real)===0);}
    public static function clearErrorLog(){$state=self::errorLogState();if(!$state['writable'])throw new RuntimeException('Das konfigurierte PHP-Fehlerprotokoll ist nicht als beschreibbare lokale Datei verfügbar.');$handle=@fopen($state['path'],'c');if(!$handle)throw new RuntimeException('Das Fehlerprotokoll konnte nicht geöffnet werden.');if(!flock($handle,LOCK_EX)){fclose($handle);throw new RuntimeException('Das Fehlerprotokoll wird gerade verwendet.');}$ok=ftruncate($handle,0);fflush($handle);flock($handle,LOCK_UN);fclose($handle);if(!$ok)throw new RuntimeException('Das Fehlerprotokoll konnte nicht geleert werden.');}
    private static function iniMatches($actual,$expected){$value=strtolower(trim((string)$actual));if($expected==='0')return in_array($value,array('','0','off','false','no','none'),true);if($expected==='1')return in_array($value,array('1','on','true','yes'),true);return $value===strtolower((string)$expected);}
    private static function iniDisplay($actual){return self::iniEnabled($actual)?'Aktiviert':'Deaktiviert';}
    private static function iniEnabled($actual){$value=strtolower(trim((string)$actual));return in_array($value,array('1','on','true','yes'),true);}
    private static function localizeLogLine($line){$line=(string)$line;try{$zone=new DateTimeZone(date_default_timezone_get());if(function_exists('wbce_timezone')){$candidate=wbce_timezone();if($candidate instanceof DateTimeZone)$zone=$candidate;}elseif(defined('TIMEZONE_IDENTIFIER'))$zone=new DateTimeZone((string)TIMEZONE_IDENTIFIER);if(preg_match('/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2}))/', $line,$match)){$date=new DateTimeImmutable($match[1]);return $date->setTimezone($zone)->format('d.m.Y H:i:s').substr($line,strlen($match[1]));}if(preg_match('/^\[([0-9]{2}-[A-Za-z]{3}-[0-9]{4} [0-9:]{8}) UTC\]/',$line,$match)){$date=DateTimeImmutable::createFromFormat('!d-M-Y H:i:s',$match[1],new DateTimeZone('UTC'));if($date)return '['.$date->setTimezone($zone)->format('d.m.Y H:i:s').']'.substr($line,strlen($match[0]));}}catch(Throwable $e){}return $line;}
    private static function bytes($bytes){$units=array('B','KB','MB','GB','TB');$i=0;while($bytes>=1024&&$i<count($units)-1){$bytes/=1024;$i++;}return number_format($bytes,$i?1:0,',','.').' '.$units[$i];}
}
