<?php
if (!defined('WB_PATH')) return;
require_once __DIR__.'/Language.php';
require_once __DIR__.'/RuntimeConfig.php';
require_once __DIR__.'/PhpRuntime.php';
require_once __DIR__.'/Service.php';
require_once __DIR__.'/Worker.php';
WbceSecurityCenterPhpRuntime::apply(WbceSecurityCenterRuntimeConfig::load());

$t=static function($key){return WbceSecurityCenterLanguage::text('worker.'.$key,$key);};
$definitions=array(
'security_center.scheduled_scan'=>array('label'=>$t('scheduled_scan_label'),'description'=>$t('scheduled_scan_description'),'default_cron'=>'0 3 * * *','default_name'=>$t('scheduled_scan_label'),'default_configuration'=>array(),'callable'=>array('WbceSecurityCenterWorker','scheduledScan')),
'security_center.code_scan'=>array('label'=>$t('code_scan_label'),'description'=>$t('code_scan_description'),'default_cron'=>'*/2 * * * *','default_name'=>$t('code_scan_label'),'default_configuration'=>array('files_per_run'=>120),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','scan')),
'security_center.virus_scan'=>array('label'=>$t('virus_scan_label'),'description'=>$t('virus_scan_description'),'default_cron'=>'*/2 * * * *','default_name'=>$t('virus_scan_label'),'default_configuration'=>array('files_per_run'=>80),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','virusScan')),
'security_center.scheduled_virus_scan'=>array('label'=>$t('scheduled_virus_scan_label'),'description'=>$t('scheduled_virus_scan_description'),'default_cron'=>'0 4 * * *','default_name'=>$t('scheduled_virus_scan_label'),'default_configuration'=>array(),'callable'=>array('WbceSecurityCenterWorker','scheduledVirusScan')),
'security_center.integrity'=>array('label'=>$t('integrity_label'),'description'=>$t('integrity_description'),'default_cron'=>'*/5 * * * *','default_name'=>$t('integrity_label'),'default_configuration'=>array('files_per_run'=>250),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','integrity')),
'security_center.traffic'=>array('label'=>$t('traffic_label'),'description'=>$t('traffic_description'),'default_cron'=>'* * * * *','default_name'=>$t('traffic_label'),'default_configuration'=>array('items_per_run'=>500),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','traffic')),
'security_center.bot_verification'=>array('label'=>$t('bot_label'),'description'=>$t('bot_description'),'default_cron'=>'* * * * *','default_name'=>$t('bot_label'),'default_configuration'=>array('items_per_run'=>20),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','botVerification')),
'security_center.diagnostics'=>array('label'=>$t('diagnostics_label'),'description'=>$t('diagnostics_description'),'default_cron'=>'* * * * *','default_name'=>$t('diagnostics_label'),'default_configuration'=>array(),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','diagnostics')),
'security_center.notifications'=>array('label'=>$t('notifications_label'),'description'=>$t('notifications_description'),'default_cron'=>'*/2 * * * *','default_name'=>$t('notifications_label'),'default_configuration'=>array(),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','notifications')),
'security_center.cleanup'=>array('label'=>$t('cleanup_label'),'description'=>$t('cleanup_description'),'default_cron'=>'23 3 * * *','default_name'=>$t('cleanup_label'),'default_configuration'=>array(),'managed_task'=>true,'callable'=>array('WbceSecurityCenterWorker','cleanup')));
if(function_exists('wbce_add_filter'))wbce_add_filter('worker.definitions',static function($current)use($definitions){return array_merge((array)$current,$definitions);});
elseif(is_file(WB_PATH.'/modules/worker/Registry.php')){require_once WB_PATH.'/modules/worker/Registry.php';foreach($definitions as $id=>$definition)WbceWorkerRegistry::register($id,$definition);}

if(function_exists('wbce_add_action')){
 $log=static function($type,$severity='info',$details=array()){global $database;try{(new WbceSecurityCenterService($database))->event($type,$severity,$details);}catch(Throwable $e){error_log('WBCE Security Center event: '.$e->getMessage());}};
 wbce_add_action('auth.login.failed',static function($username,$context=array())use($log){$log('auth.login.failed','warning',array('username_hash'=>hash('sha256',strtolower((string)$username))));});
 wbce_add_action('auth.login.succeeded',static function($userId)use($log){$log('auth.login.succeeded','info',array('user_id'=>(int)$userId));});
 wbce_add_action('auth.challenge.failed',static function($provider,$userId)use($log){$log('auth.factor.failed','warning',array('provider'=>(string)$provider,'user_id'=>(int)$userId));});
 foreach(array('addon.installed'=>'info','addon.upgraded'=>'info','addon.uninstalled'=>'warning')as$event=>$severity)wbce_add_action($event,static function($context)use($log,$event,$severity){if($event==='addon.uninstalled'&&($context['directory']??'')==='security_center')return;$log($event,$severity,(array)$context);});
 wbce_add_filter('admin.dashboard.widgets',static function($widgets){global $database;$summary=(new WbceSecurityCenterService($database))->summary();if($summary['critical']>0){$title=htmlspecialchars(WbceSecurityCenterLanguage::text('module.name','Security Center'),ENT_QUOTES,'UTF-8');$url=htmlspecialchars(ADMIN_URL.'/admintools/tool.php?tool=security_center&sc_page=scanner',ENT_QUOTES,'UTF-8');$content='<a class="security-center-dashboard-findings" href="'.$url.'"><strong>'.(int)$summary['critical'].'</strong> '.htmlspecialchars(WbceSecurityCenterLanguage::text('summary.dashboard_critical','critical or high-priority open findings.'),ENT_QUOTES,'UTF-8').'</a>';$widgets[]=array('html'=>'<section id="security-center-dashboard-widget" class="wbce-dashboard-hook-widget wbce-card"><h3><a href="'.$url.'">'.$title.'</a></h3><div class="wbce-dashboard-hook-content">'.$content.'</div></section><style>#security-center-dashboard-widget{grid-column:1/-1;box-sizing:border-box;width:100%;margin:0 0 1rem;padding:1rem 1.2rem;border:1px solid var(--wbce-admin-border,#dfe5e9);border-left:5px solid var(--wbce-admin-primary,#2271b1);border-radius:var(--wbce-admin-radius,0);background:var(--wbce-admin-surface,#fff);color:var(--wbce-admin-text,inherit);box-shadow:var(--wbce-admin-shadow,none)}#security-center-dashboard-widget h3{margin:0 0 .4rem}#security-center-dashboard-widget h3 a{color:#1769aa!important;text-decoration:none}#security-center-dashboard-widget h3 a:hover{text-decoration:underline}#security-center-dashboard-widget .wbce-dashboard-hook-content{line-height:1.45}#security-center-dashboard-widget .security-center-dashboard-findings{display:inline-block;color:#1769aa!important;font-weight:600;text-decoration:underline;text-underline-offset:.16em}#security-center-dashboard-widget .security-center-dashboard-findings:hover{text-decoration-thickness:2px}#security-center-dashboard-widget .security-center-dashboard-findings:focus-visible{outline:2px solid var(--wbce-admin-primary,#2271b1);outline-offset:3px}</style><script>(function(){var widget=document.getElementById("security-center-dashboard-widget"),shell=document.querySelector(".wbce-dashboard-shell"),grid=shell&&shell.querySelector(".wbce-dashboard-grid");if(widget&&grid)grid.insertBefore(widget,grid.firstChild);})();</script>','priority'=>15);}return $widgets;});
}
