<?php
return array(
 'database_unavailable'=>'Die WBCE-Datenbank ist nicht verfügbar.','encryption_unavailable'=>'Es ist keine unterstützte Verschlüsselungserweiterung verfügbar.',
 'provider_name'=>'Authenticator-App (TOTP)','provider_description'=>'Zeitbasierte Einmalcodes aus Google Authenticator, Ente Auth und kompatiblen Apps.','active'=>'Aktiv','not_configured'=>'Nicht eingerichtet',
 'account_active'=>'Deine Anmeldung ist zusätzlich durch einen Code aus der Authenticator-App geschützt.','account_inactive'=>'Schütze dein Benutzerkonto zusätzlich mit einer Authenticator-App und Backupcodes.','manage'=>'2FA verwalten','setup_now'=>'Jetzt einrichten',
 'challenge_description'=>'Gib den sechsstelligen Code deiner Authenticator-App oder einen Backupcode ein.','security_code'=>'Sicherheitscode','finish_login'=>'Anmeldung abschließen',
 'security_failed'=>'Die Sicherheitsprüfung ist fehlgeschlagen.','state_failed'=>'Der gespeicherte 2FA-Status konnte nicht bestätigt werden.','confirmation_invalid'=>'Der Bestätigungscode ist ungültig.','code_invalid'=>'Der Sicherheitscode ist ungültig.','data_save_failed'=>'Die 2FA-Daten konnten nicht dauerhaft gespeichert werden.','backup_save_failed'=>'Die Backupcodes konnten nicht vollständig gespeichert werden.','decrypt_failed'=>'Der TOTP-Schlüssel konnte nicht entschlüsselt werden.','key_missing'=>'Der TOTP-Verschlüsselungsschlüssel fehlt.','key_invalid'=>'Der TOTP-Verschlüsselungsschlüssel ist ungültig.','tables_missing'=>'Die 2FA-Datenbanktabellen sind nicht verfügbar.','secret_create_failed'=>'Der 2FA-Schlüssel konnte nicht angelegt werden.',
 'intro'=>'Schütze dein Konto zusätzlich mit einem zeitbasierten Einmalcode.','backup_title'=>'Backupcodes sicher aufbewahren','backup_once'=>'Diese Codes werden nur jetzt angezeigt.','backup_hint'=>'Jeder Code kann einmal verwendet werden, wenn deine Authenticator-App nicht verfügbar ist.','backup_store'=>'Speichere die Codes an einem sicheren Ort, bevor du fortfährst.','backup_confirm'=>'Ich habe die Backupcodes sicher gespeichert.',
 'setup_title'=>'2FA einrichten','confirm_password_first'=>'Bestätige zuerst dein aktuelles Passwort.','current_password'=>'Aktuelles Passwort','password_invalid'=>'Das aktuelle Passwort ist nicht korrekt.','begin'=>'Einrichtung beginnen','connect_app'=>'Authenticator-App verbinden','scan_qr'=>'Scanne diesen QR-Code mit deiner Authenticator-App:','qr_label'=>'QR-Code zur Einrichtung der 2FA Authentifizierung','manual_key'=>'Falls das Scannen nicht möglich ist, trage diesen Schlüssel manuell ein:','technical_uri'=>'Technische Einrichtungsadresse','app_code'=>'Code aus der App','enable'=>'2FA bestätigen und aktivieren','is_active'=>'2FA ist aktiv','active_hint'=>'Bei der Anmeldung wird ein zusätzlicher Code verlangt.','disabled_message'=>'2FA Authentifizierung wurde deaktiviert.','new_backup'=>'Neue Backupcodes erzeugen','auth_or_backup'=>'Authenticator- oder Backupcode','disable'=>'2FA deaktivieren','back'=>'Zurück zu den Einstellungen','provider_requires_core'=>'Dieser Provider benötigt das installierte Grundmodul 2FA Authentifizierung.','key_create_failed'=>'Der TOTP-Verschlüsselungsschlüssel konnte nicht erstellt werden.'
);
