<?php
return array(
 'database_unavailable'=>'The WBCE database is unavailable.','encryption_unavailable'=>'No supported encryption extension is available.',
 'provider_name'=>'Authenticator app (TOTP)','provider_description'=>'Time-based one-time codes from Google Authenticator, Ente Auth and compatible apps.','active'=>'Active','not_configured'=>'Not configured',
 'account_active'=>'Your sign-in is additionally protected by a code from your authenticator app.','account_inactive'=>'Protect your account with an authenticator app and recovery codes.','manage'=>'Manage 2FA','setup_now'=>'Set up now',
 'challenge_description'=>'Enter the six-digit code from your authenticator app or a recovery code.','security_code'=>'Security code','finish_login'=>'Complete sign-in',
 'security_failed'=>'The security check failed.','state_failed'=>'The saved 2FA state could not be confirmed.','confirmation_invalid'=>'The confirmation code is invalid.','code_invalid'=>'The security code is invalid.','data_save_failed'=>'The 2FA data could not be stored permanently.','backup_save_failed'=>'The recovery codes could not be saved completely.','decrypt_failed'=>'The TOTP secret could not be decrypted.','key_missing'=>'The TOTP encryption key is missing.','key_invalid'=>'The TOTP encryption key is invalid.','tables_missing'=>'The 2FA database tables are unavailable.','secret_create_failed'=>'The 2FA secret could not be created.',
 'intro'=>'Protect your account with a time-based one-time code.','backup_title'=>'Store recovery codes securely','backup_once'=>'These codes are shown only once.','backup_hint'=>'Each code can be used once if your authenticator app is unavailable.','backup_store'=>'Store the codes in a secure place before continuing.','backup_confirm'=>'I have stored the recovery codes securely.',
 'setup_title'=>'Set up 2FA','confirm_password_first'=>'First confirm your current password.','current_password'=>'Current password','password_invalid'=>'The current password is incorrect.','begin'=>'Start setup','connect_app'=>'Connect authenticator app','scan_qr'=>'Scan this QR code with your authenticator app:','qr_label'=>'QR code for setting up 2FA Authentication','manual_key'=>'If scanning is not possible, enter this key manually:','technical_uri'=>'Technical setup address','app_code'=>'Code from the app','enable'=>'Confirm and enable 2FA','is_active'=>'2FA is active','active_hint'=>'An additional code is required when signing in.','disabled_message'=>'2FA Authentication was disabled.','new_backup'=>'Generate new recovery codes','auth_or_backup'=>'Authenticator or recovery code','disable'=>'Disable 2FA','back'=>'Back to settings','provider_requires_core'=>'This provider requires the installed 2FA Authentication core module.','key_create_failed'=>'The TOTP encryption key could not be created.'
);
