<?php
$rules=$service->rules();$bans=$service->temporaryBans();
$types=array('allow_ip'=>array('IP erlauben','ip','IP-Adresse','192.0.2.10'),'block_ip'=>array('IP dauerhaft sperren','ip','IP-Adresse','192.0.2.10'),'block_cidr'=>array('IP-Bereich sperren','cidr','Netzwerk in CIDR-Notation','192.0.2.0/24'),'country'=>array('Land sperren','country','Ländercode','DE'),'user_agent'=>array('Bot/Browserkennung','text','Teil der Browserkennung','BadBot'),'browser'=>array('Browser sperren','text','Browsername','Browsername'),'os'=>array('Betriebssystem sperren','text','Betriebssystem','Betriebssystem'),'isp'=>array('Provider sperren','text','Providername','Provider'),'referrer'=>array('Referrer sperren','host','Domain','example.org'),'bad_word'=>array('Wort/Inhalt filtern','text','Wort oder Ausdruck','unerwünschter Inhalt'),'file_allow'=>array('Datei-Ausnahme','path','Relativer Dateipfad','modules/example/file.php'));
function sec_datetime_local($utc){if(!$utc)return '';try{$date=new DateTimeImmutable($utc,new DateTimeZone('UTC'));if(function_exists('wbce_timezone')){$zone=wbce_timezone();if($zone instanceof DateTimeZone)$date=$date->setTimezone($zone);}return $date->format('Y-m-d\TH:i');}catch(Throwable $e){return '';}}
?>
<section><div class="sec-section-head"><div><h3>Automatische und zeitlich begrenzte Sperren</h3><p>Einträge können einzeln freigegeben, deaktiviert, bearbeitet oder vollständig exportiert werden.</p></div><button type="button" class="sec-secondary" data-export-table="ban-list" data-export-name="security-center-sperrliste.csv">CSV exportieren</button></div>
<form method="post" class="sec-rule-form"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="ban_save"><?php echo $admin->getFTAN();?><label>IP-Adresse<input name="address" required placeholder="192.0.2.10"></label><label>Ablauf (optional)<input type="datetime-local" name="expires_at"></label><label>Notiz<input name="note"></label><input type="hidden" name="enabled" value="1"><button>Sperre hinzufügen</button></form>
<div class="sec-scroll"><table id="ban-list" data-exportable><thead><tr><th>Status</th><th>Adresse</th><th>Quelle</th><th>Grund</th><th>Ablauf</th><th>Notiz</th><th data-no-export>Aktionen</th></tr></thead><tbody><?php foreach($bans as $ban){$active=(int)$ban['enabled']===1&&(!$ban['expires_at']||strtotime($ban['expires_at'].' UTC')>time());?><tr><td><span class="sec-status-dot <?php echo $active?'on':'off';?>"></span><?php echo $active?'Aktiv':((int)$ban['enabled']===1?'Abgelaufen':'Inaktiv');?></td><td><code><?php echo sec_h($ban['address']);?></code></td><td><?php echo $ban['source']==='automatic'?'Automatisch':'Manuell';?></td><td><?php echo sec_h($ban['reason']?:'–');?></td><td><?php echo sec_time($ban['expires_at']);?></td><td><?php echo sec_h($ban['note']?:'–');?></td><td data-no-export><div class="sec-table-actions"><button type="button" class="sec-secondary" data-toggle-edit="ban-<?php echo (int)$ban['id'];?>">Bearbeiten</button><form method="post" data-confirm="Soll diese Adresse jetzt entsperrt werden?"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="ban_change"><input type="hidden" name="id" value="<?php echo (int)$ban['id'];?>"><input type="hidden" name="ban_action" value="unban"><?php echo $admin->getFTAN();?><button class="sec-danger">Entsperren</button></form></div></td></tr>
<tr id="ban-<?php echo (int)$ban['id'];?>" class="sec-edit-row" hidden><td colspan="7"><form method="post" class="sec-form-grid"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="ban_save"><input type="hidden" name="id" value="<?php echo (int)$ban['id'];?>"><?php echo $admin->getFTAN();?><label>IP-Adresse<input name="address" required value="<?php echo sec_h($ban['address']);?>"></label><label>Ablauf (leer = unbegrenzt)<input type="datetime-local" name="expires_at" value="<?php echo sec_h(sec_datetime_local($ban['expires_at']));?>"></label><label>Notiz<input name="note" value="<?php echo sec_h($ban['note']);?>"></label><label class="sec-inline-toggle">Aktiv <span class="sec-slider"><input type="checkbox" name="enabled" value="1"<?php echo (int)$ban['enabled']===1?' checked':'';?>><i></i></span></label><button>Änderungen speichern</button></form></td></tr><?php }?></tbody></table></div>
<?php if(!$bans){?><p class="sec-muted">Die Sperrliste ist leer.</p><?php }?>
<form method="post" data-confirm="Sollen wirklich alle automatischen und zeitlich begrenzten Sperren geleert werden?"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="temporary_bans_clear"><?php echo $admin->getFTAN();?><button class="sec-danger"<?php echo !$bans?' disabled':'';?>>Gesamte Sperrliste leeren</button></form></section>

<section><h3>Neue Ausnahme, dauerhafte Sperre oder Filterregel</h3><form method="post" class="sec-rule-form"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="rule_add"><?php echo $admin->getFTAN();?><label>Regelart<select name="kind" data-rule-kind><?php foreach($types as $key=>$meta)echo '<option value="'.$key.'">'.sec_h($meta[0]).'</option>';?></select></label><label data-rule-value-label>IP-Adresse<input name="pattern" required placeholder="192.0.2.10" data-rule-value></label><label>Notiz<input name="note" placeholder="Optional"></label><div class="sec-rule-help" data-rule-help></div><button>Regel hinzufügen</button></form><script type="application/json" data-rule-config><?php echo json_encode($types,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);?></script></section>

<section><div class="sec-section-head"><div><h3>Dauerhafte Sperren, Ausnahmen und Filter</h3><p>Diese Regeln werden kompiliert und ohne zusätzliche Datenbankabfrage in der Firewall angewendet.</p></div><button type="button" class="sec-secondary" data-export-table="rule-list" data-export-name="security-center-regeln.csv">CSV exportieren</button></div><div class="sec-scroll"><table id="rule-list" data-exportable><thead><tr><th>Typ</th><th>Wert</th><th>Notiz</th><th>Status</th><th data-no-export>Aktionen</th></tr></thead><tbody><?php foreach($rules as $rule){?><tr><td><?php echo sec_h($types[$rule['kind']][0]??$rule['kind']);?></td><td><?php echo sec_h($rule['pattern']);?></td><td><?php echo sec_h($rule['note']?:'–');?></td><td><span class="sec-status-dot <?php echo $rule['enabled']?'on':'off';?>"></span><?php echo $rule['enabled']?'Aktiv':'Inaktiv';?></td><td data-no-export><div class="sec-table-actions"><form method="post"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="rule_change"><input type="hidden" name="id" value="<?php echo (int)$rule['id'];?>"><?php echo $admin->getFTAN();?><label class="sec-slider"><input type="checkbox" name="rule_action" value="<?php echo $rule['enabled']?'disable':'enable';?>"<?php echo $rule['enabled']?' checked':'';?> data-auto-submit><i></i></label></form><button type="button" class="sec-secondary" data-toggle-edit="rule-<?php echo (int)$rule['id'];?>">Bearbeiten</button><form method="post" data-confirm="Soll diese Regel wirklich gelöscht werden?"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="rule_change"><input type="hidden" name="id" value="<?php echo (int)$rule['id'];?>"><?php echo $admin->getFTAN();?><button name="rule_action" value="delete" class="sec-danger">Löschen</button></form></div></td></tr>
<tr id="rule-<?php echo (int)$rule['id'];?>" class="sec-edit-row" hidden><td colspan="5"><form method="post" class="sec-form-grid"><input type="hidden" name="sc_page" value="rules"><input type="hidden" name="action" value="rule_update"><input type="hidden" name="id" value="<?php echo (int)$rule['id'];?>"><?php echo $admin->getFTAN();?><label>Wert<input name="pattern" required value="<?php echo sec_h($rule['pattern']);?>"></label><label>Notiz<input name="note" value="<?php echo sec_h($rule['note']);?>"></label><button>Änderungen speichern</button></form></td></tr><?php }?></tbody></table></div></section>
