<?php
$summary=$service->summary();
$protections=array(
    'firewall_enabled'=>array('Firewall','Prüft alle eingehenden Anfragen.','protection'),
    'sqli_protection'=>array('SQL-Injection','Erkennt typische Datenbankangriffe.','protection'),
    'xss_protection'=>array('XSS-Schutz','Blockiert aktiven Scriptcode in Anfragen.','protection'),
    'bad_bot_protection'=>array('Bot-Schutz','Erkennt schädliche Bots und Scanner.','protection'),
    'spam_protection'=>array('Spam-Schutz','Prüft Links und wiederholte Inhalte.','protection'),
    'scanner_enabled'=>array('Codescanner','Prüft Dateien portionsweise über den Worker.','scanner'),
    'virus_scanner_enabled'=>array('Virenscanner','Erkennt Malware, Webshells und getarnte Nutzlasten über den Worker.','virus_scanner'),
    'integrity_enabled'=>array('Dateiüberwachung','Erkennt neue, veränderte und gelöschte Dateien.','scanner'),
    'traffic_logging'=>array('Besucherprotokoll','Erfasst eine datensparsame Besucherstichprobe.','traffic'),
);
?>
<div class="sec-grid"><article class="sec-card sec-summary-card"><h3><?php echo sec_h(sec_t('summary.open','Offene Funde'));?></h3><div class="sec-number"><?php echo (int)$summary['open'];?></div><a href="?tool=security_center&amp;sc_page=scanner" data-sec-page="scanner"><?php echo sec_h(sec_t('summary.findings','Funde anzeigen'));?></a></article><article class="sec-card sec-summary-card"><h3><?php echo sec_h(sec_t('summary.critical','Hohe Priorität'));?></h3><div class="sec-number"><?php echo (int)$summary['critical'];?></div><a href="?tool=security_center&amp;sc_page=scanner" data-sec-page="scanner"><?php echo sec_h(sec_t('summary.details','Details anzeigen'));?></a></article><article class="sec-card sec-summary-card"><h3><?php echo sec_h(sec_t('summary.blocked','Blockierte Angriffe'));?></h3><div class="sec-number"><?php echo (int)$summary['blocked'];?></div><a href="?tool=security_center&amp;sc_page=logs" data-sec-page="logs"><?php echo sec_h(sec_t('summary.open_log','Protokoll öffnen'));?></a></article><article class="sec-card sec-summary-card"><h3><?php echo sec_h(sec_t('summary.visits','Besucherereignisse'));?></h3><div class="sec-number"><?php echo (int)$summary['visits'];?></div><a href="?tool=security_center&amp;sc_page=traffic" data-sec-page="traffic"><?php echo sec_h(sec_t('summary.open_traffic','Besucheranalyse öffnen'));?></a></article></div>
<section><h3><?php echo sec_h(sec_t('summary.protections','Schutzmodule'));?></h3><div class="sec-protection-grid"><?php foreach($protections as $key=>$meta){$active=($settings[$key]??'0')==='1';?><article class="sec-protection-card<?php echo $active?' is-active':' is-inactive';?>"><div><a href="?tool=security_center&amp;sc_page=<?php echo sec_h($meta[2]);?>" data-sec-page="<?php echo sec_h($meta[2]);?>"><h4><?php echo sec_h($meta[0]);?></h4></a><p><?php echo sec_h($meta[1]);?></p></div><footer><span class="sec-state"><i class="<?php echo $active?'on':'off';?>"></i><?php echo sec_h(sec_t($active?'common.active':'common.inactive',$active?'Aktiv':'Inaktiv'));?></span><form method="post"><input type="hidden" name="sc_page" value="status"><input type="hidden" name="action" value="setting_toggle"><input type="hidden" name="setting_name" value="<?php echo sec_h($key);?>"><?php echo $admin->getFTAN();?><label class="sec-slider" aria-label="<?php echo sec_h($meta[0]);?>"><input type="checkbox" name="setting_value" value="1"<?php echo $active?' checked':'';?> data-setting-toggle><i></i></label></form></footer></article><?php }?></div></section>
