<?php
require_once __DIR__.'/../Diagnostics.php';
$system=WbceSecurityCenterDiagnostics::system();
$phpInfoAvailable=WbceSecurityCenterDiagnostics::phpInfoAvailable();
$configuration=WbceSecurityCenterDiagnostics::configuration($settings);
$phpStaticSettings=array_values(array_filter($configuration,static function($test){return !$test['runtime_changeable'];}));
$phpIniLines=$phpFpmLines=$phpApacheLines=array();foreach($phpStaticSettings as $test){$value=$test['expected']==='1'?'On':'Off';$phpIniLines[]=$test['name'].' = '.$value;$phpFpmLines[]='php_admin_value['.$test['name'].'] = '.($test['expected']==='1'?'1':'0');$phpApacheLines[]='php_flag '.$test['name'].' '.$value;}
$functions=WbceSecurityCenterDiagnostics::functions();
$diagnosticJobs=$service->diagnosticJobs();
$importantPorts=array(21=>'FTP',22=>'SSH',25=>'SMTP',53=>'DNS',80=>'HTTP',110=>'POP3',143=>'IMAP',443=>'HTTPS',465=>'SMTPS',587=>'Mail Submission',993=>'IMAPS',995=>'POP3S',3306=>'MySQL/MariaDB',5432=>'PostgreSQL',6379=>'Redis',8080=>'HTTP alternativ',8443=>'HTTPS alternativ');
?>
<section><h3>Systeminformationen</h3><div class="sec-grid"><?php foreach($system as $label=>$value){?><article class="sec-card"><h4><?php echo sec_h($label);?></h4><p class="sec-path"><?php echo sec_h($value);?></p></article><?php }?></div><?php if($phpInfoAvailable){?><details class="sec-phpinfo"><summary>Vollständige PHP-Informationen anzeigen</summary><div class="sec-phpinfo-frame"><iframe title="PHP-Informationen" sandbox srcdoc="<?php echo sec_h(WbceSecurityCenterDiagnostics::phpInfoHtml());?>"></iframe></div></details><?php }?></section>
<section><h3>PHP-Konfigurationsprüfung</h3><p class="sec-help">Der Schalter zeigt den im Security Center gespeicherten Sollwert. Die Spalte „Aktueller PHP-Wert“ zeigt getrennt davon, welchen Wert PHP in dieser Anfrage tatsächlich verwendet. Abweichungen werden als ausstehend gekennzeichnet. Nicht zur Laufzeit veränderbare Direktiven werden ausschließlich angezeigt.</p><div class="sec-config-table"><table><thead><tr><th>Einstellung</th><th>Aktueller PHP-Wert</th><th>Ergebnis</th><th>Empfehlung</th><th>Gespeicherter Wert</th></tr></thead><tbody><?php foreach($configuration as $test){?><tr><td><code><?php echo sec_h($test['name']);?></code><?php if($test['pending']){?><small class="sec-pending">Gespeichert · PHP übernimmt aktuell einen anderen Wert</small><?php }?></td><td><?php echo sec_h($test['actual']);?></td><td><span class="sec-badge <?php echo $test['ok']?'success':'warning';?>"><?php echo $test['ok']?'In Ordnung':'Prüfen';?></span></td><td><?php echo sec_h($test['recommendation']);?></td><td><?php if($test['can_manage']&&$test['runtime_changeable']){?><form method="post"><input type="hidden" name="sc_page" value="tools"><input type="hidden" name="action" value="php_config_fix"><input type="hidden" name="setting_name" value="<?php echo sec_h($test['name']);?>"><?php echo $admin->getFTAN();?><label class="sec-slider" title="Gespeicherten Sollwert ändern"><input type="checkbox" name="setting_value" value="1"<?php echo $test['enabled']?' checked':'';?> data-auto-submit><i></i></label><strong class="sec-switch-state"><?php echo $test['enabled']?'Aktiviert':'Deaktiviert';?></strong></form><?php }else{?><span class="sec-muted">Nicht zur PHP-Laufzeit änderbar</span><?php }?></td></tr><?php }?></tbody></table></div></section>
<?php if($phpStaticSettings){?><section class="sec-php-directives"><h3>Sichere PHP-Konfigurationsvorschläge</h3><p>Diese Werte können in der aktuellen Anfrage nicht geändert werden. Verwenden Sie den Block, der zur Serverumgebung passt. Vorhandene abweichende Einträge müssen ersetzt werden. Danach PHP-FPM beziehungsweise den Webserver neu laden.</p><div class="sec-directive-grid"><article><h4>php.ini</h4><p>Für die zentrale PHP-Konfiguration.</p><textarea readonly rows="10" data-copy-source><?php echo sec_h(implode("\n",$phpIniLines));?></textarea><button type="button" data-copy-config>php.ini kopieren</button></article><article><h4>PHP-FPM-Pool</h4><p>In der Pooldatei, beispielsweise unter <code>pool.d</code>.</p><textarea readonly rows="10" data-copy-source><?php echo sec_h(implode("\n",$phpFpmLines));?></textarea><button type="button" data-copy-config>FPM-Direktiven kopieren</button></article><article><h4>Apache/mod_php</h4><p>Nur verwenden, wenn PHP als Apache-Modul läuft und <code>php_flag</code> erlaubt ist.</p><textarea readonly rows="10" data-copy-source><?php echo sec_h(implode("\n",$phpApacheLines));?></textarea><button type="button" data-copy-config>Apache-Direktiven kopieren</button></article></div><div class="sec-static-summary"><strong><?php echo count(array_filter($phpStaticSettings,static function($test){return !$test['ok'];}));?> Korrekturen erforderlich</strong><ul><?php foreach($phpStaticSettings as $test)if(!$test['ok']){?><li><code><?php echo sec_h($test['name']);?></code>: <?php echo sec_h($test['recommendation']);?></li><?php }?></ul></div></section><?php }?>
<section><h3>PHP-Funktionsprüfung</h3><div class="sec-scroll"><table><thead><tr><th>Gruppe</th><th>Funktion</th><th>Status</th></tr></thead><tbody><?php foreach($functions as $test){?><tr><td><?php echo sec_h($test['group']);?></td><td><code><?php echo sec_h($test['function']);?>()</code></td><td><span class="sec-badge <?php echo $test['available']?'warning':'success';?>"><?php echo $test['available']?'Verfügbar – Bedarf prüfen':'Deaktiviert';?></span></td></tr><?php }?></tbody></table></div></section>
<?php $htaccessPath=WB_PATH.'/.htaccess';$htaccessContent=$service->htaccess();?><section class="sec-htaccess-section"><h3>.htaccess-Editor</h3><p><strong>Datei:</strong> <code class="sec-path"><?php echo sec_h($htaccessPath);?></code> · <span class="sec-badge <?php echo is_file($htaccessPath)?'success':'warning';?>"><?php echo is_file($htaccessPath)?'Vorhanden':'Noch nicht vorhanden';?></span></p><p>Beim Speichern wird eine vorhandene Datei zuerst als <code>.htaccess.security-center-backup</code> gesichert. Ist die Datei noch nicht vorhanden, wird sie im WBCE-Hauptverzeichnis neu angelegt.</p><form method="post" data-confirm="Soll die .htaccess-Datei wirklich gespeichert werden?" class="sec-htaccess-form"><input type="hidden" name="sc_page" value="tools"><input type="hidden" name="action" value="htaccess_save"><?php echo $admin->getFTAN();?><label class="sec-span">Inhalt</label><div class="sec-code-shell" data-htaccess-shell><pre class="sec-htaccess-highlight" data-htaccess-highlight aria-hidden="true"></pre><textarea name="htaccess_content" rows="22" spellcheck="false" wrap="off" class="sec-code-editor" data-htaccess-editor aria-label="Inhalt der .htaccess-Datei"><?php echo sec_h($htaccessContent);?></textarea></div><button>Mit Sicherungskopie speichern</button></form></section>
<section><h3>Hash-Werkzeug</h3><div class="sec-form-grid"><label class="sec-span">Text<textarea rows="4" data-hash-input></textarea></label><label class="sec-span">SHA-256<input readonly data-hash-output></label></div><button type="button" data-create-hash>SHA-256 erzeugen</button></section>
<section><h3>Asynchrone Netzwerkdiagnosen</h3><p>Die Prüfungen werden durch den Worker ausgeführt. Der Porttest ist aus Sicherheitsgründen auf den eigenen Webserver und höchstens 20 Ports begrenzt.</p>
<form method="post" class="sec-diagnostic-form"><input type="hidden" name="sc_page" value="tools"><input type="hidden" name="action" value="diagnostic_queue"><?php echo $admin->getFTAN();?>
<label>Prüfung<select name="diagnostic_type" data-diagnostic-type><option value="ip_lookup">IP-/DNS-Auskunft</option><option value="fake_bot">Suchmaschinen-Bot verifizieren</option><option value="dnsbl">DNSBL-Spamprüfung</option><option value="port_scan">Ports des eigenen Servers prüfen</option></select></label>
<label data-diagnostic-target>IP-Adresse<input name="diagnostic_target" placeholder="192.0.2.10"></label><div class="sec-span" data-diagnostic-ports hidden><strong>Wichtige lokale Ports</strong><p class="sec-help">Geprüft wird ausschließlich die lokale Adresse 127.0.0.1. Ein offener Port ist nicht automatisch unsicher, sollte aber einem benötigten Dienst zugeordnet sein.</p><div class="sec-port-list"><?php foreach($importantPorts as $port=>$serviceName){?><label class="sec-port-choice"><input type="checkbox" name="diagnostic_port_values[]" value="<?php echo $port;?>"<?php echo in_array($port,array(21,22,25,80,443,3306),true)?' checked':'';?>> <span><strong><?php echo $port;?></strong> · <?php echo sec_h($serviceName);?></span></label><?php }?></div></div><button>Diagnose einplanen</button></form>
<div class="sec-export-actions"><button type="button" class="sec-secondary" data-export-table="diagnostic-list" data-export-name="security-center-diagnosen.csv">CSV</button><button type="button" class="sec-secondary" data-export-table="diagnostic-list" data-export-format="xls" data-export-name="security-center-diagnosen.xls">Excel</button><button type="button" class="sec-secondary" data-export-table="diagnostic-list" data-export-format="pdf">PDF / Drucken</button></div><div class="sec-scroll"><table id="diagnostic-list"><thead><tr><th>Prüfung</th><th>Ziel</th><th>Status</th><th>Erstellt</th><th>Ergebnis</th><th data-no-export></th></tr></thead><tbody><?php foreach($diagnosticJobs as $job){$decoded=json_decode((string)$job['result'],true);$result=is_array($decoded)?json_encode($decoded,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):(string)$job['result'];?><tr><td><?php echo sec_h($job['job_type']==='port_scan'?'Lokaler Portscan':$job['job_type']);?></td><td><?php echo sec_h($job['job_type']==='port_scan'?'Dieser Server':$job['target']);?></td><td><?php echo sec_h($job['status']);?></td><td><?php echo sec_h(sec_time($job['created_at']));?></td><td class="sec-path"><?php if($job['job_type']==='port_scan'&&is_array($decoded)&&isset($decoded['ports'])){?><div class="sec-port-result"><?php foreach($decoded['ports'] as $port=>$state){$open=!empty($state['open']);?><span class="sec-port-state <?php echo $open?'open':'closed';?>"><code><?php echo (int)$port;?></code> <?php echo sec_h($importantPorts[(int)$port]??'Port');?>: <?php echo $open?'Offen':'Geschlossen';?></span><br><?php }?></div><?php }else{?><code><?php echo sec_h($result?:'–');?></code><?php }?></td><td data-no-export><?php if($job['status']!=='running'){?><form method="post" data-confirm="Soll dieser Diagnoseauftrag gelöscht werden?"><input type="hidden" name="sc_page" value="tools"><input type="hidden" name="action" value="diagnostic_delete"><input type="hidden" name="id" value="<?php echo (int)$job['id'];?>"><?php echo $admin->getFTAN();?><button class="sec-danger">Löschen</button></form><?php }?></td></tr><?php }?></tbody></table></div></section>
