<?php
$visits=$service->visits();
$analytics=array('Browser'=>array(),'Betriebssystem'=>array(),'Gerät'=>array(),'Referrer'=>array());
foreach($visits as $visit){
    $ua=(string)$visit['user_agent'];
    $browser=preg_match('/Edg\//i',$ua)?'Edge':(preg_match('/Firefox\//i',$ua)?'Firefox':(preg_match('/Chrome\//i',$ua)?'Chrome':(preg_match('/Safari\//i',$ua)?'Safari':'Andere')));
    $os=preg_match('/Windows/i',$ua)?'Windows':(preg_match('/Android/i',$ua)?'Android':(preg_match('/iPhone|iPad/i',$ua)?'iOS/iPadOS':(preg_match('/Mac OS/i',$ua)?'macOS':(preg_match('/Linux/i',$ua)?'Linux':'Andere'))));
    $device=preg_match('/Mobile|Android|iPhone/i',$ua)?'Mobil':(preg_match('/iPad|Tablet/i',$ua)?'Tablet':'Desktop');
    $referrer=trim((string)$visit['referrer_host'])?:'Direkt';
    foreach(array('Browser'=>$browser,'Betriebssystem'=>$os,'Gerät'=>$device,'Referrer'=>$referrer) as $group=>$value)$analytics[$group][$value]=($analytics[$group][$value]??0)+1;
}
?>
<form method="post"><input type="hidden" name="sc_page" value="traffic"><input type="hidden" name="action" value="settings"><input type="hidden" name="setting_scope" value="traffic"><?php echo $admin->getFTAN();?>
<section><h3>Besucheraufzeichnung</h3><div class="sec-options"><?php sec_switch($settings,'traffic_logging','Besucherprotokoll aktivieren','Speichert eine datenschutzfreundliche Stichprobe ohne Klartext-IP.');?></div><div class="sec-form-grid"><label>Stichprobe<input type="number" name="traffic_sample_rate" min="1" max="100" value="<?php echo (int)$settings['traffic_sample_rate'];?>"><small>Prozent</small></label><label>Aufbewahrung<input type="number" name="traffic_retention_days" min="1" max="90" value="<?php echo (int)$settings['traffic_retention_days'];?>"><small>Tage</small></label></div><button>Besuchereinstellungen speichern</button></section></form>
<section><h3>Besucheranalyse</h3><p class="sec-muted">Ein vorhandener Unterpunkt filtert den Live-Verkehr direkt. Mehrere Filter lassen sich kombinieren.</p><div class="sec-grid"><?php foreach($analytics as $group=>$values){arsort($values);$filterKey=array('Browser'=>'browser','Betriebssystem'=>'os','Gerät'=>'device','Referrer'=>'referrer')[$group];?><article class="sec-card"><h4><?php echo sec_h($group);?></h4><ul class="sec-analytics"><?php foreach(array_slice($values,0,6,true) as $label=>$count){?><li><button type="button" class="sec-analytics-choice" data-traffic-filter="<?php echo sec_h($filterKey);?>" data-traffic-value="<?php echo sec_h($label);?>"><span><?php echo sec_h($label);?></span><strong><?php echo (int)$count;?></strong></button></li><?php }?><?php if(!$values){?><li class="sec-muted">Noch keine Daten</li><?php }?></ul></article><?php }?></div><div class="sec-active-filters" data-active-traffic-filters hidden><span></span><button type="button" data-traffic-clear>Filter zurücksetzen</button></div></section>
<section class="sec-traffic-live"><div class="sec-section-head"><div><h3>Live-Verkehr</h3><small class="sec-muted" data-traffic-live-status>Wird automatisch alle drei Sekunden aktualisiert.</small></div><span class="sec-live-indicator"><i></i>Echtzeit</span></div><p class="sec-muted">IP-Adressen werden ausschließlich als installationsgebundene HMAC-Werte gespeichert.</p><div class="sec-scroll"><table data-traffic-table><thead><tr><th>Zeit</th><th>Methode</th><th>Pfad</th><th>Referrer</th><th>Browserkennung</th></tr></thead><tbody><?php foreach($visits as $visit){$ua=(string)$visit['user_agent'];$browser=preg_match('/Edg\//i',$ua)?'Edge':(preg_match('/Firefox\//i',$ua)?'Firefox':(preg_match('/Chrome\//i',$ua)?'Chrome':(preg_match('/Safari\//i',$ua)?'Safari':'Andere')));$os=preg_match('/Windows/i',$ua)?'Windows':(preg_match('/Android/i',$ua)?'Android':(preg_match('/iPhone|iPad/i',$ua)?'iOS/iPadOS':(preg_match('/Mac OS/i',$ua)?'macOS':(preg_match('/Linux/i',$ua)?'Linux':'Andere'))));$device=preg_match('/Mobile|Android|iPhone/i',$ua)?'Mobil':(preg_match('/iPad|Tablet/i',$ua)?'Tablet':'Desktop');$referrer=trim((string)$visit['referrer_host'])?:'Direkt';?><tr data-browser="<?php echo sec_h($browser);?>" data-os="<?php echo sec_h($os);?>" data-device="<?php echo sec_h($device);?>" data-referrer="<?php echo sec_h($referrer);?>"><td><?php echo sec_h(sec_time($visit['created_at']));?></td><td><?php echo sec_h($visit['method']);?></td><td><?php echo sec_h($visit['path']);?></td><td><?php echo sec_h($visit['referrer_host']);?></td><td class="sec-path"><?php echo sec_h($visit['user_agent']);?></td></tr><?php }?></tbody></table></div></section>
