<?php
final class WbceTwoFactorUserSection
{
 public static function render($database,$userId)
 {
  if(!WbceTwoFactorSettings::enabled($database))return '';
  $providers=array_filter(WbceTwoFactorRegistry::providers(),static function($p){return empty($p['admin_config'])||(!empty($p['system_configured'])&&is_callable($p['system_configured'])&&(bool)call_user_func($p['system_configured']));});
  $selected=WbceTwoFactorSettings::userProvider($database,$userId);$cards='';
  foreach($providers as $id=>$p){if(!WbceTwoFactorSettings::providerEnabled($database,$id))continue;$configured=!empty($p['configured'])&&is_callable($p['configured'])&&(bool)call_user_func($p['configured'],$userId);$active=$selected===$id;$profile=(string)($p['profile_url']??'#');$url=self::h($profile.(strpos($profile,'?')===false?'?':'&').'embedded=1');$cards.='<article class="content-box wbce-admin-card tf-user-card'.($active?' wbce-admin-card--active is-selected':'').'" data-user-provider="'.self::h($id).'"><h3>'.self::h($p['name']??$id).'</h3><p class="wbce-admin-muted">'.self::h(wbce_two_factor_t($configured?'user_provider_ready':'user_provider_setup')).'</p><div class="tf-user-actions"><button type="button" class="button wbce-admin-button" data-user-config="'.$url.'">'.self::h(wbce_two_factor_t($configured?'manage':'setup_provider')).'</button>'.($configured?'<button type="button" class="button wbce-admin-button" data-user-select="'.self::h($id).'"'.($active?' disabled':'').'>'.self::h(wbce_two_factor_t($active?'selected':'use_provider')).'</button>':'').'</div></article>';}
  if($cards==='')return '';
  global $admin;$token=isset($admin)&&is_object($admin)&&method_exists($admin,'getFTAN')?$admin->getFTAN():'';$endpoint=self::h(WB_URL.'/modules/two_factor/user.php');$dialog=$selected===''?'<p class="tf-user-disable wbce-admin-muted" role="status">'.self::h(wbce_two_factor_t('personal_disabled_status')).'</p>':'<div class="tf-user-disable-dialog">'.self::dialog().'</div>';$labels=array('saveFailed'=>wbce_two_factor_t('save_failed'),'securityKey'=>wbce_two_factor_t('use_security_key'),'factorInvalid'=>wbce_two_factor_t('factor_invalid'),'selected'=>wbce_two_factor_t('selected'),'useProvider'=>wbce_two_factor_t('use_provider'),'deactivated'=>wbce_two_factor_t('deactivated'));
  return '<section class="tf-user-section wbce-admin-tool-shell" data-endpoint="'.$endpoint.'" data-labels="'.self::h(json_encode($labels,JSON_UNESCAPED_UNICODE)).'"><header class="wbce-admin-hero"><i class="fa fa-shield" aria-hidden="true"></i><div class="wbce-admin-hero__content"><h2>'.self::h(wbce_two_factor_t('user_section_title')).'</h2><p>'.self::h(wbce_two_factor_t('user_section_intro')).'</p></div></header><div class="tf-user-grid wbce-admin-component-grid">'.$cards.'</div><div class="tf-user-config" hidden><div class="tf-user-config-body" aria-live="polite"></div></div><form data-user-token hidden>'.$token.'</form>'.$dialog.'<div class="tf-user-toast" hidden aria-live="polite"></div></section><link rel="stylesheet" href="'.self::h(WB_URL.'/modules/two_factor/admin-ui.css?v=1.1.34').'"><link rel="stylesheet" href="'.self::h(WB_URL.'/modules/two_factor/user-section.css?v=1.1.34').'"><script src="'.self::h(WB_URL.'/modules/two_factor/user-section.js?v=1.1.34').'" defer></script>';
 }
 private static function dialog(){return '<button type="button" class="button wbce-admin-button tf-user-disable" data-user-disable>'.self::h(wbce_two_factor_t('disable_personal')).'</button><dialog class="tf-disable-dialog wbce-admin-card"><form method="dialog" data-disable-form><h3>'.self::h(wbce_two_factor_t('disable_confirm_title')).'</h3><p>'.self::h(wbce_two_factor_t('disable_confirm_intro')).'</p><div data-disable-password><label>'.self::h(wbce_two_factor_t('current_password')).'<input type="password" name="password" autocomplete="current-password" required></label><div class="tf-dialog-actions"><button type="button" class="button wbce-admin-button" data-disable-cancel>'.self::h(wbce_two_factor_t('cancel')).'</button><button type="submit" class="button wbce-admin-button">'.self::h(wbce_two_factor_t('continue')).'</button></div></div><div data-disable-factor hidden><h4>'.self::h(wbce_two_factor_t('factor_confirmation')).'</h4><p data-disable-message hidden></p><label data-code-field>'.self::h(wbce_two_factor_t('current_factor_code')).'<input name="factor_code" inputmode="numeric" autocomplete="one-time-code"></label><div class="tf-dialog-actions"><button type="button" class="button wbce-admin-button" data-disable-cancel>'.self::h(wbce_two_factor_t('cancel')).'</button><button type="submit" class="button wbce-admin-button" data-disable-confirm>'.self::h(wbce_two_factor_t('confirm_disable')).'</button></div></div><p class="error" data-disable-error hidden role="alert"></p></form></dialog>';}
 private static function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
}
