(function(){
 document.querySelectorAll('.tf-user-section').forEach(function(root){
  var panel=root.querySelector('.tf-user-config'),body=panel.querySelector('.tf-user-config-body'),activeUrl='',token=root.querySelector('[data-user-token]'),endpoint=root.dataset.endpoint,labels={};try{labels=JSON.parse(root.dataset.labels||'{}')}catch(ignore){}
  function result(response){return response.text().then(function(text){var start=text.indexOf('{'),end=text.lastIndexOf('}')+1;if(start<0||end<=start)throw new Error(labels.saveFailed);var data=JSON.parse(text.slice(start,end));if(data.ftan)token.innerHTML=data.ftan;if(!response.ok||!data.success)throw new Error(data.message||labels.saveFailed);return data})}
  function post(data){var secured=new FormData(token);data.forEach(function(value,key){secured.append(key,value)});return fetch(endpoint,{method:'POST',body:secured,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(result)}
  function toast(message){var node=root.querySelector('.tf-user-toast');node.textContent=message||'';node.hidden=false;window.setTimeout(function(){node.hidden=true},6000)}
  function selectProvider(provider,message){root.querySelectorAll('[data-user-provider]').forEach(function(card){var active=card.dataset.userProvider===provider;card.classList.toggle('is-selected',active);card.classList.toggle('wbce-admin-card--active',active);var button=card.querySelector('[data-user-select]');if(button){button.disabled=active;button.textContent=active?(labels.selected||button.textContent):(labels.useProvider||button.textContent)}});toast(message)}
  function showContentError(message){body.removeAttribute('aria-busy');body.innerHTML='';var node=document.createElement('p');node.className='error';node.setAttribute('role','alert');node.textContent=message;body.appendChild(node)}
  function runScripts(container,base){var scripts=Array.prototype.slice.call(container.querySelectorAll('script')),chain=Promise.resolve();scripts.forEach(function(old){old.remove();chain=chain.then(function(){return new Promise(function(resolve){var script=document.createElement('script');Array.prototype.slice.call(old.attributes).forEach(function(a){if(a.name!=='src')script.setAttribute(a.name,a.value)});if(old.src){script.src=new URL(old.getAttribute('src'),base).href;script.onload=resolve;script.onerror=resolve}else script.text=old.textContent;container.appendChild(script);if(!old.src)resolve()})})});return chain}
  function bind(container){container.querySelectorAll('form').forEach(function(form){form.addEventListener('submit',function(event){event.preventDefault();var button=form.querySelector('[type=submit],button:not([type])');if(button)button.disabled=true;load(form.getAttribute('action')||activeUrl,{method:'POST',body:new FormData(form)}).finally(function(){if(button&&document.contains(button))button.disabled=false})})})}
  function render(html,url){var parsed=new DOMParser().parseFromString(html,'text/html'),content=parsed.querySelector('main')||parsed.body,fragment=document.createElement('div');fragment.className='tf-user-config-content';fragment.innerHTML=content.innerHTML;body.replaceChildren(fragment);body.removeAttribute('aria-busy');return runScripts(fragment,url).then(function(){bind(fragment)})}
  function load(url,options){activeUrl=url;panel.hidden=false;body.setAttribute('aria-busy','true');return fetch(url,Object.assign({credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}},options||{})).then(function(response){activeUrl=response.url||url;return response.text().then(function(html){if(!response.ok)throw new Error(labels.saveFailed);return render(html,activeUrl)})}).catch(function(reason){showContentError(reason.message);throw reason})}
  root.querySelectorAll('[data-user-config]').forEach(function(button){button.addEventListener('click',function(){if(!panel.hidden&&activeUrl===button.dataset.userConfig){panel.hidden=true;body.replaceChildren();activeUrl='';return}load(button.dataset.userConfig).then(function(){panel.scrollIntoView({behavior:'smooth',block:'nearest'})})})});
  root.querySelectorAll('[data-user-select]').forEach(function(button){button.addEventListener('click',function(){var provider=button.dataset.userSelect,data=new FormData();data.append('provider',provider);button.disabled=true;post(data).then(function(response){selectProvider(response.provider||provider,response.message)}).catch(function(reason){toast(reason.message);button.disabled=false})})});
  var dialog=root.querySelector('.tf-disable-dialog');if(!dialog)return;var form=dialog.querySelector('[data-disable-form]'),passwordStep=dialog.querySelector('[data-disable-password]'),factorStep=dialog.querySelector('[data-disable-factor]'),errorBox=dialog.querySelector('[data-disable-error]'),codeField=dialog.querySelector('[data-code-field]'),message=dialog.querySelector('[data-disable-message]'),challenge=null;
  function showError(reason){errorBox.textContent=reason.message||String(reason);errorBox.hidden=false;form.removeAttribute('aria-busy')}
  function decode(value){return Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((value.length+3)%4)),function(c){return c.charCodeAt(0)})}function encode(value){return btoa(String.fromCharCode.apply(null,new Uint8Array(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  function useKey(options){options.challenge=decode(options.challenge);options.allowCredentials=(options.allowCredentials||[]).map(function(item){item.id=decode(item.id);return item});return navigator.credentials.get({publicKey:options}).then(function(value){return JSON.stringify({id:value.id,type:value.type,response:{clientDataJSON:encode(value.response.clientDataJSON),authenticatorData:encode(value.response.authenticatorData),signature:encode(value.response.signature),userHandle:value.response.userHandle?encode(value.response.userHandle):null}})})}
  root.querySelector('[data-user-disable]').addEventListener('click',function(){form.reset();passwordStep.hidden=false;factorStep.hidden=true;errorBox.hidden=true;challenge=null;dialog.showModal();form.elements.password.focus()});dialog.querySelectorAll('[data-disable-cancel]').forEach(function(button){button.addEventListener('click',function(){dialog.close()})});
  form.addEventListener('submit',function(event){event.preventDefault();errorBox.hidden=true;form.setAttribute('aria-busy','true');var password=form.elements.password.value;if(!challenge){var prepare=new FormData();prepare.append('action','prepare_disable');prepare.append('password',password);post(prepare).then(function(data){challenge=data.challenge||{};passwordStep.hidden=true;factorStep.hidden=false;if(challenge.message){message.textContent=challenge.message;message.hidden=false}else message.hidden=true;if(challenge.type==='webauthn'){codeField.hidden=true;form.querySelector('[data-disable-confirm]').textContent=labels.securityKey}else{codeField.hidden=false;form.elements.factor_code.required=true;form.elements.factor_code.focus()}form.removeAttribute('aria-busy')}).catch(showError);return}function verify(value){var data=new FormData();data.append('action','disable');data.append('password',password);data.append('factor_code',value);post(data).then(function(response){dialog.close();selectProvider('',response.message||labels.deactivated);var holder=root.querySelector('.tf-user-disable-dialog');if(holder)holder.hidden=true;var status=document.createElement('p');status.className='tf-user-disable-status wbce-admin-muted';status.setAttribute('role','status');status.textContent=response.message||labels.deactivated;holder?holder.before(status):root.appendChild(status)}).catch(showError)}if(challenge.type==='webauthn')useKey(challenge.options||{}).then(verify).catch(function(){showError(new Error(labels.factorInvalid))});else verify(form.elements.factor_code.value)});
 });
})();
